// ============================================================
// DATA: 700 words + 300 chunks
// ============================================================
window.ITEMS = [
// ── WORDS (type:"word") ──────────────────────────────────────
// Pronouns & determiners
{id:"w001",type:"word",en:"I",ja:"私は"},
{id:"w002",type:"word",en:"you",ja:"あなた"},
{id:"w003",type:"word",en:"he",ja:"彼は"},
{id:"w004",type:"word",en:"she",ja:"彼女は"},
{id:"w005",type:"word",en:"we",ja:"私たちは"},
{id:"w006",type:"word",en:"they",ja:"彼らは"},
{id:"w007",type:"word",en:"it",ja:"それは"},
{id:"w008",type:"word",en:"me",ja:"私を/に"},
{id:"w009",type:"word",en:"him",ja:"彼を/に"},
{id:"w010",type:"word",en:"her",ja:"彼女を/に"},
{id:"w011",type:"word",en:"us",ja:"私たちを/に"},
{id:"w012",type:"word",en:"them",ja:"彼らを/に"},
{id:"w013",type:"word",en:"my",ja:"私の"},
{id:"w014",type:"word",en:"your",ja:"あなたの"},
{id:"w015",type:"word",en:"his",ja:"彼の"},
{id:"w016",type:"word",en:"our",ja:"私たちの"},
{id:"w017",type:"word",en:"their",ja:"彼らの"},
{id:"w018",type:"word",en:"this",ja:"これ / この"},
{id:"w019",type:"word",en:"that",ja:"あれ / その"},
{id:"w020",type:"word",en:"these",ja:"これら"},
{id:"w021",type:"word",en:"those",ja:"あれら"},
{id:"w022",type:"word",en:"some",ja:"いくつかの"},
{id:"w023",type:"word",en:"any",ja:"どんな / 何か"},
{id:"w024",type:"word",en:"every",ja:"すべての"},
{id:"w025",type:"word",en:"each",ja:"それぞれの"},
{id:"w026",type:"word",en:"both",ja:"両方"},
{id:"w027",type:"word",en:"all",ja:"すべて"},
{id:"w028",type:"word",en:"few",ja:"少しの"},
{id:"w029",type:"word",en:"many",ja:"多くの"},
{id:"w030",type:"word",en:"much",ja:"たくさんの（不可算）"},
// Basic verbs
{id:"w031",type:"word",en:"be",ja:"〜である"},
{id:"w032",type:"word",en:"have",ja:"持っている"},
{id:"w033",type:"word",en:"do",ja:"する"},
{id:"w034",type:"word",en:"say",ja:"言う"},
{id:"w035",type:"word",en:"get",ja:"得る / なる"},
{id:"w036",type:"word",en:"make",ja:"作る / させる"},
{id:"w037",type:"word",en:"go",ja:"行く"},
{id:"w038",type:"word",en:"know",ja:"知っている"},
{id:"w039",type:"word",en:"take",ja:"取る / 持っていく"},
{id:"w040",type:"word",en:"see",ja:"見える / 会う"},
{id:"w041",type:"word",en:"come",ja:"来る"},
{id:"w042",type:"word",en:"think",ja:"考える / 思う"},
{id:"w043",type:"word",en:"look",ja:"見る / 見える"},
{id:"w044",type:"word",en:"want",ja:"欲しい / したい"},
{id:"w045",type:"word",en:"give",ja:"与える"},
{id:"w046",type:"word",en:"use",ja:"使う"},
{id:"w047",type:"word",en:"find",ja:"見つける / 感じる"},
{id:"w048",type:"word",en:"tell",ja:"伝える / 教える"},
{id:"w049",type:"word",en:"ask",ja:"尋ねる / 頼む"},
{id:"w050",type:"word",en:"seem",ja:"〜に見える"},
{id:"w051",type:"word",en:"feel",ja:"感じる"},
{id:"w052",type:"word",en:"try",ja:"試みる"},
{id:"w053",type:"word",en:"leave",ja:"去る / 残す"},
{id:"w054",type:"word",en:"call",ja:"呼ぶ / 電話する"},
{id:"w055",type:"word",en:"keep",ja:"保つ / 続ける"},
{id:"w056",type:"word",en:"let",ja:"させる"},
{id:"w057",type:"word",en:"begin",ja:"始める"},
{id:"w058",type:"word",en:"show",ja:"見せる"},
{id:"w059",type:"word",en:"hear",ja:"聞こえる"},
{id:"w060",type:"word",en:"play",ja:"遊ぶ / 演奏する"},
{id:"w061",type:"word",en:"run",ja:"走る"},
{id:"w062",type:"word",en:"move",ja:"動く / 引越す"},
{id:"w063",type:"word",en:"live",ja:"生きる / 住む"},
{id:"w064",type:"word",en:"believe",ja:"信じる"},
{id:"w065",type:"word",en:"hold",ja:"持つ / 保つ"},
{id:"w066",type:"word",en:"bring",ja:"持ってくる"},
{id:"w067",type:"word",en:"happen",ja:"起こる"},
{id:"w068",type:"word",en:"write",ja:"書く"},
{id:"w069",type:"word",en:"sit",ja:"座る"},
{id:"w070",type:"word",en:"stand",ja:"立つ"},
{id:"w071",type:"word",en:"lose",ja:"失う / 負ける"},
{id:"w072",type:"word",en:"pay",ja:"払う"},
{id:"w073",type:"word",en:"meet",ja:"会う"},
{id:"w074",type:"word",en:"include",ja:"含む"},
{id:"w075",type:"word",en:"continue",ja:"続ける"},
{id:"w076",type:"word",en:"learn",ja:"学ぶ"},
{id:"w077",type:"word",en:"change",ja:"変える / 変わる"},
{id:"w078",type:"word",en:"lead",ja:"導く"},
{id:"w079",type:"word",en:"understand",ja:"理解する"},
{id:"w080",type:"word",en:"watch",ja:"見る / 監視する"},
{id:"w081",type:"word",en:"follow",ja:"ついていく / 理解する"},
{id:"w082",type:"word",en:"stop",ja:"止まる / やめる"},
{id:"w083",type:"word",en:"create",ja:"作る / 創造する"},
{id:"w084",type:"word",en:"speak",ja:"話す"},
{id:"w085",type:"word",en:"read",ja:"読む"},
{id:"w086",type:"word",en:"spend",ja:"(お金・時間を)使う"},
{id:"w087",type:"word",en:"grow",ja:"育つ / 増える"},
{id:"w088",type:"word",en:"open",ja:"開ける / 開く"},
{id:"w089",type:"word",en:"walk",ja:"歩く"},
{id:"w090",type:"word",en:"win",ja:"勝つ"},
{id:"w091",type:"word",en:"offer",ja:"提供する / 申し出る"},
{id:"w092",type:"word",en:"remember",ja:"覚えている / 思い出す"},
{id:"w093",type:"word",en:"love",ja:"愛する / 大好きである"},
{id:"w094",type:"word",en:"consider",ja:"検討する / 〜とみなす"},
{id:"w095",type:"word",en:"appear",ja:"現れる / 〜に見える"},
{id:"w096",type:"word",en:"buy",ja:"買う"},
{id:"w097",type:"word",en:"wait",ja:"待つ"},
{id:"w098",type:"word",en:"serve",ja:"仕える / 提供する"},
{id:"w099",type:"word",en:"send",ja:"送る"},
{id:"w100",type:"word",en:"build",ja:"建てる / 築く"},
{id:"w101",type:"word",en:"stay",ja:"滞在する / とどまる"},
{id:"w102",type:"word",en:"fall",ja:"落ちる / (季節の)秋"},
{id:"w103",type:"word",en:"cut",ja:"切る"},
{id:"w104",type:"word",en:"reach",ja:"届く / 連絡する"},
{id:"w105",type:"word",en:"pass",ja:"通り過ぎる / 渡す"},
{id:"w106",type:"word",en:"sell",ja:"売る"},
{id:"w107",type:"word",en:"decide",ja:"決める"},
{id:"w108",type:"word",en:"pull",ja:"引く"},
{id:"w109",type:"word",en:"push",ja:"押す"},
{id:"w110",type:"word",en:"pick",ja:"選ぶ / 摘む"},
{id:"w111",type:"word",en:"turn",ja:"回る / 曲がる"},
{id:"w112",type:"word",en:"put",ja:"置く"},
{id:"w113",type:"word",en:"start",ja:"始める"},
{id:"w114",type:"word",en:"raise",ja:"上げる / 育てる"},
{id:"w115",type:"word",en:"help",ja:"助ける"},
{id:"w116",type:"word",en:"need",ja:"必要とする"},
{id:"w117",type:"word",en:"talk",ja:"話す / 話し合う"},
{id:"w118",type:"word",en:"work",ja:"働く / 機能する"},
{id:"w119",type:"word",en:"mean",ja:"意味する"},
{id:"w120",type:"word",en:"happen",ja:"起こる"},
// Common nouns
{id:"w121",type:"word",en:"time",ja:"時間 / 回"},
{id:"w122",type:"word",en:"year",ja:"年"},
{id:"w123",type:"word",en:"people",ja:"人々"},
{id:"w124",type:"word",en:"way",ja:"方法 / 道"},
{id:"w125",type:"word",en:"day",ja:"日 / 昼"},
{id:"w126",type:"word",en:"man",ja:"男性 / 人"},
{id:"w127",type:"word",en:"woman",ja:"女性"},
{id:"w128",type:"word",en:"child",ja:"子ども"},
{id:"w129",type:"word",en:"world",ja:"世界"},
{id:"w130",type:"word",en:"life",ja:"人生 / 生活"},
{id:"w131",type:"word",en:"hand",ja:"手"},
{id:"w132",type:"word",en:"place",ja:"場所"},
{id:"w133",type:"word",en:"week",ja:"週"},
{id:"w134",type:"word",en:"home",ja:"家 / 家庭"},
{id:"w135",type:"word",en:"water",ja:"水"},
{id:"w136",type:"word",en:"room",ja:"部屋"},
{id:"w137",type:"word",en:"money",ja:"お金"},
{id:"w138",type:"word",en:"story",ja:"話 / 物語"},
{id:"w139",type:"word",en:"fact",ja:"事実"},
{id:"w140",type:"word",en:"month",ja:"月"},
{id:"w141",type:"word",en:"thing",ja:"もの / こと"},
{id:"w142",type:"word",en:"book",ja:"本"},
{id:"w143",type:"word",en:"eye",ja:"目"},
{id:"w144",type:"word",en:"job",ja:"仕事"},
{id:"w145",type:"word",en:"word",ja:"言葉 / 単語"},
{id:"w146",type:"word",en:"head",ja:"頭"},
{id:"w147",type:"word",en:"house",ja:"家"},
{id:"w148",type:"word",en:"friend",ja:"友達"},
{id:"w149",type:"word",en:"father",ja:"父"},
{id:"w150",type:"word",en:"power",ja:"力 / 電力"},
{id:"w151",type:"word",en:"hour",ja:"時間（1時間）"},
{id:"w152",type:"word",en:"game",ja:"ゲーム"},
{id:"w153",type:"word",en:"line",ja:"線 / 列"},
{id:"w154",type:"word",en:"name",ja:"名前"},
{id:"w155",type:"word",en:"city",ja:"市 / 都市"},
{id:"w156",type:"word",en:"school",ja:"学校"},
{id:"w157",type:"word",en:"family",ja:"家族"},
{id:"w158",type:"word",en:"body",ja:"体"},
{id:"w159",type:"word",en:"music",ja:"音楽"},
{id:"w160",type:"word",en:"food",ja:"食べ物"},
{id:"w161",type:"word",en:"heart",ja:"心 / ハート"},
{id:"w162",type:"word",en:"morning",ja:"朝"},
{id:"w163",type:"word",en:"night",ja:"夜"},
{id:"w164",type:"word",en:"face",ja:"顔 / 直面する"},
{id:"w165",type:"word",en:"car",ja:"車"},
{id:"w166",type:"word",en:"street",ja:"通り"},
{id:"w167",type:"word",en:"country",ja:"国 / 田舎"},
{id:"w168",type:"word",en:"town",ja:"町"},
{id:"w169",type:"word",en:"door",ja:"ドア"},
{id:"w170",type:"word",en:"air",ja:"空気"},
{id:"w171",type:"word",en:"ground",ja:"地面"},
{id:"w172",type:"word",en:"side",ja:"側 / 面"},
{id:"w173",type:"word",en:"point",ja:"点 / 要点"},
{id:"w174",type:"word",en:"end",ja:"終わり / 終える"},
{id:"w175",type:"word",en:"question",ja:"質問"},
{id:"w176",type:"word",en:"number",ja:"数 / 番号"},
{id:"w177",type:"word",en:"lot",ja:"たくさん"},
{id:"w178",type:"word",en:"area",ja:"地域 / 分野"},
{id:"w179",type:"word",en:"case",ja:"場合 / ケース"},
{id:"w180",type:"word",en:"idea",ja:"アイデア / 考え"},
{id:"w181",type:"word",en:"mother",ja:"母"},
{id:"w182",type:"word",en:"part",ja:"部分 / 役割"},
{id:"w183",type:"word",en:"back",ja:"背中 / 後ろ"},
{id:"w184",type:"word",en:"problem",ja:"問題"},
{id:"w185",type:"word",en:"truth",ja:"真実"},
{id:"w186",type:"word",en:"group",ja:"グループ"},
{id:"w187",type:"word",en:"state",ja:"状態 / 州"},
{id:"w188",type:"word",en:"result",ja:"結果"},
{id:"w189",type:"word",en:"age",ja:"年齢 / 時代"},
{id:"w190",type:"word",en:"reason",ja:"理由"},
{id:"w191",type:"word",en:"sense",ja:"意味 / 感覚"},
{id:"w192",type:"word",en:"minute",ja:"分"},
{id:"w193",type:"word",en:"moment",ja:"瞬間 / 少しの時間"},
{id:"w194",type:"word",en:"second",ja:"秒 / 2番目"},
{id:"w195",type:"word",en:"half",ja:"半分"},
{id:"w196",type:"word",en:"couple",ja:"カップル / 2〜3"},
{id:"w197",type:"word",en:"stuff",ja:"もの / こと（口語）"},
{id:"w198",type:"word",en:"deal",ja:"取引 / 扱う"},
{id:"w199",type:"word",en:"plan",ja:"計画"},
{id:"w200",type:"word",en:"system",ja:"システム / 仕組み"},
{id:"w201",type:"word",en:"office",ja:"オフィス / 事務所"},
{id:"w202",type:"word",en:"person",ja:"人"},
{id:"w203",type:"word",en:"company",ja:"会社"},
{id:"w204",type:"word",en:"team",ja:"チーム"},
{id:"w205",type:"word",en:"service",ja:"サービス"},
{id:"w206",type:"word",en:"issue",ja:"問題 / 課題"},
{id:"w207",type:"word",en:"experience",ja:"経験"},
{id:"w208",type:"word",en:"information",ja:"情報"},
{id:"w209",type:"word",en:"news",ja:"ニュース"},
{id:"w210",type:"word",en:"process",ja:"過程 / 処理する"},
{id:"w211",type:"word",en:"list",ja:"リスト"},
{id:"w212",type:"word",en:"phone",ja:"電話"},
{id:"w213",type:"word",en:"message",ja:"メッセージ"},
{id:"w214",type:"word",en:"picture",ja:"写真 / 絵"},
{id:"w215",type:"word",en:"movie",ja:"映画"},
{id:"w216",type:"word",en:"show",ja:"番組 / 見せる"},
{id:"w217",type:"word",en:"party",ja:"パーティー / 政党"},
{id:"w218",type:"word",en:"dinner",ja:"夕食"},
{id:"w219",type:"word",en:"lunch",ja:"昼食"},
{id:"w220",type:"word",en:"coffee",ja:"コーヒー"},
{id:"w221",type:"word",en:"store",ja:"店"},
{id:"w222",type:"word",en:"road",ja:"道路"},
{id:"w223",type:"word",en:"class",ja:"授業 / クラス"},
{id:"w224",type:"word",en:"language",ja:"言語"},
{id:"w225",type:"word",en:"history",ja:"歴史"},
{id:"w226",type:"word",en:"science",ja:"科学"},
{id:"w227",type:"word",en:"art",ja:"芸術 / 美術"},
{id:"w228",type:"word",en:"color",ja:"色"},
{id:"w229",type:"word",en:"sound",ja:"音 / 〜に聞こえる"},
{id:"w230",type:"word",en:"light",ja:"光 / 明るい"},
{id:"w231",type:"word",en:"nothing",ja:"何もない"},
{id:"w232",type:"word",en:"something",ja:"何か"},
{id:"w233",type:"word",en:"everything",ja:"すべて"},
{id:"w234",type:"word",en:"everyone",ja:"みんな"},
{id:"w235",type:"word",en:"someone",ja:"誰か"},
{id:"w236",type:"word",en:"anyone",ja:"誰か / 誰でも"},
{id:"w237",type:"word",en:"nobody",ja:"誰も〜ない"},
// Adjectives
{id:"w238",type:"word",en:"good",ja:"良い"},
{id:"w239",type:"word",en:"new",ja:"新しい"},
{id:"w240",type:"word",en:"first",ja:"最初の"},
{id:"w241",type:"word",en:"last",ja:"最後の / この前の"},
{id:"w242",type:"word",en:"long",ja:"長い"},
{id:"w243",type:"word",en:"great",ja:"素晴らしい / 偉大な"},
{id:"w244",type:"word",en:"little",ja:"小さい / 少し"},
{id:"w245",type:"word",en:"right",ja:"正しい / 右"},
{id:"w246",type:"word",en:"big",ja:"大きい"},
{id:"w247",type:"word",en:"high",ja:"高い"},
{id:"w248",type:"word",en:"small",ja:"小さい"},
{id:"w249",type:"word",en:"large",ja:"大きい / 広い"},
{id:"w250",type:"word",en:"next",ja:"次の"},
{id:"w251",type:"word",en:"early",ja:"早い / 早めに"},
{id:"w252",type:"word",en:"young",ja:"若い"},
{id:"w253",type:"word",en:"important",ja:"重要な"},
{id:"w254",type:"word",en:"real",ja:"本物の / 本当に"},
{id:"w255",type:"word",en:"best",ja:"最高の"},
{id:"w256",type:"word",en:"free",ja:"無料の / 自由な"},
{id:"w257",type:"word",en:"sure",ja:"確かな / もちろん"},
{id:"w258",type:"word",en:"better",ja:"より良い"},
{id:"w259",type:"word",en:"true",ja:"本当の / 真実"},
{id:"w260",type:"word",en:"common",ja:"よくある / 共通の"},
{id:"w261",type:"word",en:"hard",ja:"難しい / 硬い"},
{id:"w262",type:"word",en:"short",ja:"短い / 低い"},
{id:"w263",type:"word",en:"old",ja:"古い / 年をとった"},
{id:"w264",type:"word",en:"same",ja:"同じ"},
{id:"w265",type:"word",en:"special",ja:"特別な"},
{id:"w266",type:"word",en:"clear",ja:"明確な / 晴れた"},
{id:"w267",type:"word",en:"easy",ja:"簡単な"},
{id:"w268",type:"word",en:"different",ja:"違う"},
{id:"w269",type:"word",en:"nice",ja:"良い / 素敵な"},
{id:"w270",type:"word",en:"happy",ja:"幸せな"},
{id:"w271",type:"word",en:"bad",ja:"悪い"},
{id:"w272",type:"word",en:"ready",ja:"準備ができた"},
{id:"w273",type:"word",en:"possible",ja:"可能な"},
{id:"w274",type:"word",en:"whole",ja:"全体の"},
{id:"w275",type:"word",en:"funny",ja:"おかしい / 面白い"},
{id:"w276",type:"word",en:"busy",ja:"忙しい"},
{id:"w277",type:"word",en:"sure",ja:"確かな"},
{id:"w278",type:"word",en:"full",ja:"満ちた / いっぱいの"},
{id:"w279",type:"word",en:"strong",ja:"強い"},
{id:"w280",type:"word",en:"late",ja:"遅い / 最近の"},
{id:"w281",type:"word",en:"hot",ja:"熱い / 辛い"},
{id:"w282",type:"word",en:"cold",ja:"冷たい / 寒い"},
{id:"w283",type:"word",en:"sick",ja:"病気の"},
{id:"w284",type:"word",en:"sorry",ja:"申し訳ない"},
{id:"w285",type:"word",en:"perfect",ja:"完璧な"},
{id:"w286",type:"word",en:"low",ja:"低い"},
{id:"w287",type:"word",en:"public",ja:"公共の"},
{id:"w288",type:"word",en:"private",ja:"個人的な / 非公開の"},
{id:"w289",type:"word",en:"major",ja:"主要な"},
{id:"w290",type:"word",en:"local",ja:"地元の"},
{id:"w291",type:"word",en:"personal",ja:"個人的な"},
{id:"w292",type:"word",en:"national",ja:"全国の / 国家の"},
{id:"w293",type:"word",en:"social",ja:"社会的な"},
{id:"w294",type:"word",en:"open",ja:"開いた"},
{id:"w295",type:"word",en:"fine",ja:"良い / 細い"},
{id:"w296",type:"word",en:"alone",ja:"一人で"},
{id:"w297",type:"word",en:"able",ja:"〜できる"},
{id:"w298",type:"word",en:"available",ja:"利用可能な"},
{id:"w299",type:"word",en:"current",ja:"現在の / 流れ"},
{id:"w300",type:"word",en:"recent",ja:"最近の"},
// Adverbs
{id:"w301",type:"word",en:"just",ja:"ちょうど / ただ"},
{id:"w302",type:"word",en:"now",ja:"今"},
{id:"w303",type:"word",en:"still",ja:"まだ / 静かな"},
{id:"w304",type:"word",en:"again",ja:"また / 再び"},
{id:"w305",type:"word",en:"even",ja:"〜でさえ / 偶数の"},
{id:"w306",type:"word",en:"well",ja:"よく / 上手に"},
{id:"w307",type:"word",en:"also",ja:"また / 〜も"},
{id:"w308",type:"word",en:"only",ja:"ただ〜だけ"},
{id:"w309",type:"word",en:"very",ja:"とても"},
{id:"w310",type:"word",en:"already",ja:"すでに"},
{id:"w311",type:"word",en:"too",ja:"〜も / 〜すぎる"},
{id:"w312",type:"word",en:"really",ja:"本当に"},
{id:"w313",type:"word",en:"never",ja:"決して〜ない"},
{id:"w314",type:"word",en:"always",ja:"いつも"},
{id:"w315",type:"word",en:"often",ja:"よく / しばしば"},
{id:"w316",type:"word",en:"sometimes",ja:"時々"},
{id:"w317",type:"word",en:"usually",ja:"通常"},
{id:"w318",type:"word",en:"maybe",ja:"たぶん"},
{id:"w319",type:"word",en:"probably",ja:"おそらく"},
{id:"w320",type:"word",en:"actually",ja:"実は / 実際に"},
{id:"w321",type:"word",en:"basically",ja:"基本的に"},
{id:"w322",type:"word",en:"honestly",ja:"正直に言うと"},
{id:"w323",type:"word",en:"literally",ja:"文字通り（口語で強調にも）"},
{id:"w324",type:"word",en:"obviously",ja:"明らかに"},
{id:"w325",type:"word",en:"finally",ja:"ついに / 最後に"},
{id:"w326",type:"word",en:"suddenly",ja:"突然"},
{id:"w327",type:"word",en:"quickly",ja:"素早く"},
{id:"w328",type:"word",en:"slowly",ja:"ゆっくりと"},
{id:"w329",type:"word",en:"clearly",ja:"はっきりと"},
{id:"w330",type:"word",en:"almost",ja:"ほとんど / もう少しで"},
{id:"w331",type:"word",en:"together",ja:"一緒に"},
{id:"w332",type:"word",en:"enough",ja:"十分に"},
{id:"w333",type:"word",en:"quite",ja:"かなり / まったく"},
{id:"w334",type:"word",en:"pretty",ja:"かなり / かわいい"},
{id:"w335",type:"word",en:"rather",ja:"むしろ / かなり"},
{id:"w336",type:"word",en:"exactly",ja:"ちょうど / まったくその通り"},
{id:"w337",type:"word",en:"simply",ja:"簡単に / 単に"},
{id:"w338",type:"word",en:"certainly",ja:"確かに"},
{id:"w339",type:"word",en:"however",ja:"しかしながら"},
{id:"w340",type:"word",en:"therefore",ja:"それゆえ"},
{id:"w341",type:"word",en:"instead",ja:"代わりに"},
{id:"w342",type:"word",en:"anyway",ja:"とにかく"},
{id:"w343",type:"word",en:"else",ja:"他の / そうでなければ"},
{id:"w344",type:"word",en:"yet",ja:"まだ / でも"},
{id:"w345",type:"word",en:"though",ja:"〜だけれども"},
{id:"w346",type:"word",en:"although",ja:"〜だけれども"},
{id:"w347",type:"word",en:"while",ja:"〜の間 / 一方で"},
{id:"w348",type:"word",en:"since",ja:"〜以来 / だから"},
{id:"w349",type:"word",en:"because",ja:"なぜなら"},
{id:"w350",type:"word",en:"unless",ja:"〜でない限り"},
// Prepositions / conjunctions
{id:"w351",type:"word",en:"about",ja:"〜について"},
{id:"w352",type:"word",en:"after",ja:"〜の後"},
{id:"w353",type:"word",en:"before",ja:"〜の前"},
{id:"w354",type:"word",en:"between",ja:"〜の間に"},
{id:"w355",type:"word",en:"through",ja:"〜を通って"},
{id:"w356",type:"word",en:"during",ja:"〜の間中"},
{id:"w357",type:"word",en:"against",ja:"〜に反して / 〜に対して"},
{id:"w358",type:"word",en:"without",ja:"〜なしで"},
{id:"w359",type:"word",en:"within",ja:"〜以内に"},
{id:"w360",type:"word",en:"toward",ja:"〜に向かって"},
{id:"w361",type:"word",en:"across",ja:"〜を横切って"},
{id:"w362",type:"word",en:"beyond",ja:"〜を超えて"},
{id:"w363",type:"word",en:"along",ja:"〜に沿って"},
{id:"w364",type:"word",en:"among",ja:"〜の中で"},
// More important words
{id:"w365",type:"word",en:"kind",ja:"種類 / 親切な"},
{id:"w366",type:"word",en:"sort",ja:"種類 / 分ける"},
{id:"w367",type:"word",en:"type",ja:"種類 / タイプ"},
{id:"w368",type:"word",en:"bit",ja:"少し"},
{id:"w369",type:"word",en:"piece",ja:"一切れ / 一部"},
{id:"w370",type:"word",en:"set",ja:"セット / 設定する"},
{id:"w371",type:"word",en:"step",ja:"一歩 / 手順"},
{id:"w372",type:"word",en:"level",ja:"レベル / 水平な"},
{id:"w373",type:"word",en:"value",ja:"価値"},
{id:"w374",type:"word",en:"moment",ja:"瞬間"},
{id:"w375",type:"word",en:"chance",ja:"チャンス / 偶然"},
{id:"w376",type:"word",en:"choice",ja:"選択"},
{id:"w377",type:"word",en:"difference",ja:"違い"},
{id:"w378",type:"word",en:"situation",ja:"状況"},
{id:"w379",type:"word",en:"relationship",ja:"関係"},
{id:"w380",type:"word",en:"community",ja:"コミュニティ / 地域"},
{id:"w381",type:"word",en:"interest",ja:"興味 / 利息"},
{id:"w382",type:"word",en:"support",ja:"支援 / 支える"},
{id:"w383",type:"word",en:"effort",ja:"努力"},
{id:"w384",type:"word",en:"energy",ja:"エネルギー"},
{id:"w385",type:"word",en:"control",ja:"制御 / コントロールする"},
{id:"w386",type:"word",en:"action",ja:"行動"},
{id:"w387",type:"word",en:"place",ja:"場所 / 置く"},
{id:"w388",type:"word",en:"space",ja:"空間 / 宇宙"},
{id:"w389",type:"word",en:"situation",ja:"状況"},
{id:"w390",type:"word",en:"opinion",ja:"意見"},
{id:"w391",type:"word",en:"example",ja:"例"},
{id:"w392",type:"word",en:"answer",ja:"答え"},
{id:"w393",type:"word",en:"question",ja:"質問"},
{id:"w394",type:"word",en:"addition",ja:"追加"},
{id:"w395",type:"word",en:"amount",ja:"量 / 金額"},
{id:"w396",type:"word",en:"benefit",ja:"利益 / 恩恵"},
{id:"w397",type:"word",en:"cause",ja:"原因 / 引き起こす"},
{id:"w398",type:"word",en:"check",ja:"確認 / チェックする"},
{id:"w399",type:"word",en:"close",ja:"近い / 閉じる"},
{id:"w400",type:"word",en:"decision",ja:"決断"},
{id:"w401",type:"word",en:"detail",ja:"詳細"},
{id:"w402",type:"word",en:"doctor",ja:"医者"},
{id:"w403",type:"word",en:"drive",ja:"運転する"},
{id:"w404",type:"word",en:"event",ja:"イベント"},
{id:"w405",type:"word",en:"field",ja:"分野 / 畑"},
{id:"w406",type:"word",en:"future",ja:"将来 / 未来"},
{id:"w407",type:"word",en:"goal",ja:"目標"},
{id:"w408",type:"word",en:"health",ja:"健康"},
{id:"w409",type:"word",en:"help",ja:"助け / 助ける"},
{id:"w410",type:"word",en:"hospital",ja:"病院"},
{id:"w411",type:"word",en:"knowledge",ja:"知識"},
{id:"w412",type:"word",en:"law",ja:"法律"},
{id:"w413",type:"word",en:"leader",ja:"リーダー"},
{id:"w414",type:"word",en:"letter",ja:"手紙 / 文字"},
{id:"w415",type:"word",en:"matter",ja:"問題 / 重要である"},
{id:"w416",type:"word",en:"nature",ja:"自然 / 性質"},
{id:"w417",type:"word",en:"network",ja:"ネットワーク"},
{id:"w418",type:"word",en:"opportunity",ja:"機会"},
{id:"w419",type:"word",en:"option",ja:"選択肢"},
{id:"w420",type:"word",en:"order",ja:"順番 / 注文する"},
{id:"w421",type:"word",en:"past",ja:"過去 / 過ぎた"},
{id:"w422",type:"word",en:"position",ja:"位置 / 立場"},
{id:"w423",type:"word",en:"practice",ja:"練習"},
{id:"w424",type:"word",en:"price",ja:"値段"},
{id:"w425",type:"word",en:"quality",ja:"質 / 品質"},
{id:"w426",type:"word",en:"report",ja:"報告書 / 報告する"},
{id:"w427",type:"word",en:"response",ja:"返答 / 反応"},
{id:"w428",type:"word",en:"role",ja:"役割"},
{id:"w429",type:"word",en:"rule",ja:"規則"},
{id:"w430",type:"word",en:"sign",ja:"サイン / 合図"},
{id:"w431",type:"word",en:"size",ja:"サイズ"},
{id:"w432",type:"word",en:"skill",ja:"スキル"},
{id:"w433",type:"word",en:"source",ja:"情報源 / 源"},
{id:"w434",type:"word",en:"success",ja:"成功"},
{id:"w435",type:"word",en:"task",ja:"タスク / 仕事"},
{id:"w436",type:"word",en:"today",ja:"今日"},
{id:"w437",type:"word",en:"tomorrow",ja:"明日"},
{id:"w438",type:"word",en:"yesterday",ja:"昨日"},
{id:"w439",type:"word",en:"technology",ja:"技術"},
{id:"w440",type:"word",en:"test",ja:"テスト"},
{id:"w441",type:"word",en:"thought",ja:"考え / 思考"},
{id:"w442",type:"word",en:"top",ja:"頂上 / トップ"},
{id:"w443",type:"word",en:"trip",ja:"旅行 / つまずく"},
{id:"w444",type:"word",en:"truth",ja:"真実"},
{id:"w445",type:"word",en:"voice",ja:"声"},
{id:"w446",type:"word",en:"weight",ja:"重さ"},
{id:"w447",type:"word",en:"view",ja:"眺め / 意見"},
{id:"w448",type:"word",en:"visit",ja:"訪問 / 訪れる"},
{id:"w449",type:"word",en:"course",ja:"コース / もちろん"},
{id:"w450",type:"word",en:"interest",ja:"興味"},
{id:"w451",type:"word",en:"care",ja:"ケア / 気にする"},
{id:"w452",type:"word",en:"mind",ja:"心 / 気にする"},
{id:"w453",type:"word",en:"note",ja:"メモ / 音符"},
{id:"w454",type:"word",en:"notice",ja:"気づく / 通知"},
{id:"w455",type:"word",en:"miss",ja:"恋しい / 見逃す"},
{id:"w456",type:"word",en:"expect",ja:"期待する"},
{id:"w457",type:"word",en:"happen",ja:"起こる"},
{id:"w458",type:"word",en:"agree",ja:"同意する"},
{id:"w459",type:"word",en:"worry",ja:"心配する"},
{id:"w460",type:"word",en:"wonder",ja:"不思議に思う"},
{id:"w461",type:"word",en:"enjoy",ja:"楽しむ"},
{id:"w462",type:"word",en:"suggest",ja:"提案する"},
{id:"w463",type:"word",en:"explain",ja:"説明する"},
{id:"w464",type:"word",en:"describe",ja:"描写する"},
{id:"w465",type:"word",en:"choose",ja:"選ぶ"},
{id:"w466",type:"word",en:"accept",ja:"受け入れる"},
{id:"w467",type:"word",en:"allow",ja:"許可する"},
{id:"w468",type:"word",en:"avoid",ja:"避ける"},
{id:"w469",type:"word",en:"catch",ja:"捕まえる"},
{id:"w470",type:"word",en:"contain",ja:"含む"},
{id:"w471",type:"word",en:"cover",ja:"カバーする / 覆う"},
{id:"w472",type:"word",en:"deal",ja:"扱う / 取引"},
{id:"w473",type:"word",en:"depend",ja:"頼る / 次第である"},
{id:"w474",type:"word",en:"enter",ja:"入る"},
{id:"w475",type:"word",en:"exist",ja:"存在する"},
{id:"w476",type:"word",en:"fail",ja:"失敗する"},
{id:"w477",type:"word",en:"force",ja:"力 / 強制する"},
{id:"w478",type:"word",en:"forget",ja:"忘れる"},
{id:"w479",type:"word",en:"gather",ja:"集まる / 集める"},
{id:"w480",type:"word",en:"guess",ja:"推測する"},
{id:"w481",type:"word",en:"hit",ja:"打つ / ヒット"},
{id:"w482",type:"word",en:"imagine",ja:"想像する"},
{id:"w483",type:"word",en:"improve",ja:"改善する"},
{id:"w484",type:"word",en:"increase",ja:"増やす / 増える"},
{id:"w485",type:"word",en:"join",ja:"参加する"},
{id:"w486",type:"word",en:"jump",ja:"飛ぶ"},
{id:"w487",type:"word",en:"kill",ja:"殺す / 台無しにする"},
{id:"w488",type:"word",en:"mention",ja:"言及する"},
{id:"w489",type:"word",en:"prepare",ja:"準備する"},
{id:"w490",type:"word",en:"produce",ja:"生産する"},
{id:"w491",type:"word",en:"protect",ja:"守る"},
{id:"w492",type:"word",en:"realize",ja:"気づく / 実現する"},
{id:"w493",type:"word",en:"recognize",ja:"認識する"},
{id:"w494",type:"word",en:"reduce",ja:"減らす"},
{id:"w495",type:"word",en:"refer",ja:"言及する / 参照する"},
{id:"w496",type:"word",en:"reflect",ja:"反映する / 反省する"},
{id:"w497",type:"word",en:"remain",ja:"残る"},
{id:"w498",type:"word",en:"replace",ja:"置き換える"},
{id:"w499",type:"word",en:"require",ja:"必要とする"},
{id:"w500",type:"word",en:"respect",ja:"尊重 / 尊重する"},
{id:"w501",type:"word",en:"return",ja:"戻る / 返す"},
{id:"w502",type:"word",en:"save",ja:"節約する / 救う"},
{id:"w503",type:"word",en:"share",ja:"共有する / 分ける"},
{id:"w504",type:"word",en:"sleep",ja:"眠る"},
{id:"w505",type:"word",en:"solve",ja:"解く / 解決する"},
{id:"w506",type:"word",en:"suffer",ja:"苦しむ"},
{id:"w507",type:"word",en:"suppose",ja:"仮定する / たぶん〜だ"},
{id:"w508",type:"word",en:"surprise",ja:"驚かせる / 驚き"},
{id:"w509",type:"word",en:"touch",ja:"触れる"},
{id:"w510",type:"word",en:"treat",ja:"扱う / おごる"},
{id:"w511",type:"word",en:"trust",ja:"信頼 / 信頼する"},
{id:"w512",type:"word",en:"support",ja:"支援する"},
{id:"w513",type:"word",en:"wake",ja:"起きる / 目を覚ます"},
{id:"w514",type:"word",en:"wish",ja:"願う / 望む"},
{id:"w515",type:"word",en:"study",ja:"勉強する / 研究"},
{id:"w516",type:"word",en:"practice",ja:"練習する"},
{id:"w517",type:"word",en:"travel",ja:"旅行する"},
{id:"w518",type:"word",en:"manage",ja:"管理する / なんとかする"},
{id:"w519",type:"word",en:"handle",ja:"扱う / 取っ手"},
{id:"w520",type:"word",en:"affect",ja:"影響する"},
{id:"w521",type:"word",en:"focus",ja:"集中する"},
{id:"w522",type:"word",en:"develop",ja:"発展させる"},
{id:"w523",type:"word",en:"provide",ja:"提供する"},
{id:"w524",type:"word",en:"involve",ja:"含む / 関係する"},
{id:"w525",type:"word",en:"achieve",ja:"達成する"},
{id:"w526",type:"word",en:"compare",ja:"比較する"},
{id:"w527",type:"word",en:"connect",ja:"つながる / 接続する"},
{id:"w528",type:"word",en:"discover",ja:"発見する"},
{id:"w529",type:"word",en:"indicate",ja:"示す"},
{id:"w530",type:"word",en:"promote",ja:"促進する / 昇進させる"},
{id:"w531",type:"word",en:"encourage",ja:"励ます"},
{id:"w532",type:"word",en:"identify",ja:"特定する"},
{id:"w533",type:"word",en:"establish",ja:"設立する"},
{id:"w534",type:"word",en:"determine",ja:"決定する"},
{id:"w535",type:"word",en:"represent",ja:"代表する"},
{id:"w536",type:"word",en:"assume",ja:"仮定する / 引き受ける"},
{id:"w537",type:"word",en:"present",ja:"プレゼントする / 現在の"},
{id:"w538",type:"word",en:"receive",ja:"受け取る"},
{id:"w539",type:"word",en:"complete",ja:"完成する / 完全な"},
{id:"w540",type:"word",en:"promise",ja:"約束する"},
{id:"w541",type:"word",en:"introduce",ja:"紹介する"},
{id:"w542",type:"word",en:"discuss",ja:"議論する"},
{id:"w543",type:"word",en:"question",ja:"質問する"},
{id:"w544",type:"word",en:"claim",ja:"主張する"},
{id:"w545",type:"word",en:"confirm",ja:"確認する"},
{id:"w546",type:"word",en:"announce",ja:"発表する"},
{id:"w547",type:"word",en:"recommend",ja:"お勧めする"},
{id:"w548",type:"word",en:"apologize",ja:"謝罪する"},
{id:"w549",type:"word",en:"celebrate",ja:"祝う"},
{id:"w550",type:"word",en:"complain",ja:"不満を言う"},
// More nouns & everyday words
{id:"w551",type:"word",en:"apartment",ja:"アパート"},
{id:"w552",type:"word",en:"bank",ja:"銀行 / 岸"},
{id:"w553",type:"word",en:"bathroom",ja:"バスルーム"},
{id:"w554",type:"word",en:"bed",ja:"ベッド"},
{id:"w555",type:"word",en:"chair",ja:"椅子"},
{id:"w556",type:"word",en:"desk",ja:"机"},
{id:"w557",type:"word",en:"drink",ja:"飲み物 / 飲む"},
{id:"w558",type:"word",en:"email",ja:"メール"},
{id:"w559",type:"word",en:"floor",ja:"床 / 階"},
{id:"w560",type:"word",en:"garden",ja:"庭"},
{id:"w561",type:"word",en:"gym",ja:"ジム"},
{id:"w562",type:"word",en:"hotel",ja:"ホテル"},
{id:"w563",type:"word",en:"key",ja:"鍵 / 重要な"},
{id:"w564",type:"word",en:"kitchen",ja:"キッチン"},
{id:"w565",type:"word",en:"laptop",ja:"ノートパソコン"},
{id:"w566",type:"word",en:"map",ja:"地図"},
{id:"w567",type:"word",en:"park",ja:"公園 / 駐車する"},
{id:"w568",type:"word",en:"payment",ja:"支払い"},
{id:"w569",type:"word",en:"restaurant",ja:"レストラン"},
{id:"w570",type:"word",en:"seat",ja:"席 / 座る"},
{id:"w571",type:"word",en:"station",ja:"駅"},
{id:"w572",type:"word",en:"supermarket",ja:"スーパーマーケット"},
{id:"w573",type:"word",en:"table",ja:"テーブル"},
{id:"w574",type:"word",en:"ticket",ja:"チケット"},
{id:"w575",type:"word",en:"window",ja:"窓"},
{id:"w576",type:"word",en:"weather",ja:"天気"},
{id:"w577",type:"word",en:"weekend",ja:"週末"},
{id:"w578",type:"word",en:"meeting",ja:"会議 / 出会い"},
{id:"w579",type:"word",en:"deadline",ja:"締め切り"},
{id:"w580",type:"word",en:"schedule",ja:"スケジュール"},
{id:"w581",type:"word",en:"appointment",ja:"予約 / 約束"},
{id:"w582",type:"word",en:"habit",ja:"習慣"},
{id:"w583",type:"word",en:"attitude",ja:"態度"},
{id:"w584",type:"word",en:"behavior",ja:"行動 / 振る舞い"},
{id:"w585",type:"word",en:"personality",ja:"個性 / 性格"},
{id:"w586",type:"word",en:"situation",ja:"状況"},
{id:"w587",type:"word",en:"culture",ja:"文化"},
{id:"w588",type:"word",en:"tradition",ja:"伝統"},
{id:"w589",type:"word",en:"society",ja:"社会"},
{id:"w590",type:"word",en:"economy",ja:"経済"},
{id:"w591",type:"word",en:"education",ja:"教育"},
{id:"w592",type:"word",en:"environment",ja:"環境"},
{id:"w593",type:"word",en:"government",ja:"政府"},
{id:"w594",type:"word",en:"industry",ja:"産業"},
{id:"w595",type:"word",en:"media",ja:"メディア"},
{id:"w596",type:"word",en:"population",ja:"人口"},
{id:"w597",type:"word",en:"project",ja:"プロジェクト"},
{id:"w598",type:"word",en:"research",ja:"研究 / 調査"},
{id:"w599",type:"word",en:"solution",ja:"解決策"},
{id:"w600",type:"word",en:"strategy",ja:"戦略"},
{id:"w601",type:"word",en:"software",ja:"ソフトウェア"},
{id:"w602",type:"word",en:"data",ja:"データ"},
{id:"w603",type:"word",en:"program",ja:"プログラム"},
{id:"w604",type:"word",en:"feature",ja:"特徴 / 機能"},
{id:"w605",type:"word",en:"version",ja:"バージョン"},
{id:"w606",type:"word",en:"account",ja:"アカウント / 説明する"},
{id:"w607",type:"word",en:"content",ja:"内容 / 満足している"},
{id:"w608",type:"word",en:"comment",ja:"コメント"},
{id:"w609",type:"word",en:"review",ja:"レビュー / 振り返る"},
{id:"w610",type:"word",en:"update",ja:"更新 / アップデートする"},
{id:"w611",type:"word",en:"issue",ja:"問題 / 課題"},
{id:"w612",type:"word",en:"change",ja:"変化 / 変える"},
{id:"w613",type:"word",en:"impact",ja:"影響"},
{id:"w614",type:"word",en:"challenge",ja:"挑戦 / 難題"},
{id:"w615",type:"word",en:"mistake",ja:"間違い"},
{id:"w616",type:"word",en:"success",ja:"成功"},
{id:"w617",type:"word",en:"failure",ja:"失敗"},
{id:"w618",type:"word",en:"progress",ja:"進歩 / 進む"},
{id:"w619",type:"word",en:"attention",ja:"注意"},
{id:"w620",type:"word",en:"memory",ja:"記憶"},
{id:"w621",type:"word",en:"stress",ja:"ストレス"},
{id:"w622",type:"word",en:"pressure",ja:"プレッシャー / 圧力"},
{id:"w623",type:"word",en:"confidence",ja:"自信"},
{id:"w624",type:"word",en:"courage",ja:"勇気"},
{id:"w625",type:"word",en:"patience",ja:"忍耐"},
{id:"w626",type:"word",en:"respect",ja:"尊重"},
{id:"w627",type:"word",en:"trust",ja:"信頼"},
{id:"w628",type:"word",en:"emotion",ja:"感情"},
{id:"w629",type:"word",en:"feeling",ja:"感じ / 感情"},
{id:"w630",type:"word",en:"smile",ja:"微笑み / 微笑む"},
{id:"w631",type:"word",en:"laugh",ja:"笑う / 笑い"},
{id:"w632",type:"word",en:"cry",ja:"泣く"},
{id:"w633",type:"word",en:"dream",ja:"夢 / 夢を見る"},
{id:"w634",type:"word",en:"hope",ja:"希望 / 望む"},
{id:"w635",type:"word",en:"fear",ja:"恐れ / 恐れる"},
{id:"w636",type:"word",en:"anger",ja:"怒り"},
{id:"w637",type:"word",en:"joy",ja:"喜び"},
{id:"w638",type:"word",en:"pain",ja:"痛み"},
{id:"w639",type:"word",en:"peace",ja:"平和"},
{id:"w640",type:"word",en:"fun",ja:"楽しみ / 楽しい"},
{id:"w641",type:"word",en:"cool",ja:"かっこいい / 涼しい"},
{id:"w642",type:"word",en:"crazy",ja:"クレイジー / すごい"},
{id:"w643",type:"word",en:"serious",ja:"真剣な / 深刻な"},
{id:"w644",type:"word",en:"strange",ja:"奇妙な"},
{id:"w645",type:"word",en:"normal",ja:"普通の"},
{id:"w646",type:"word",en:"fair",ja:"公平な / まあまあ"},
{id:"w647",type:"word",en:"fresh",ja:"新鮮な"},
{id:"w648",type:"word",en:"positive",ja:"ポジティブな"},
{id:"w649",type:"word",en:"negative",ja:"ネガティブな"},
{id:"w650",type:"word",en:"nervous",ja:"緊張した"},
{id:"w651",type:"word",en:"excited",ja:"興奮した"},
{id:"w652",type:"word",en:"tired",ja:"疲れた"},
{id:"w653",type:"word",en:"bored",ja:"退屈した"},
{id:"w654",type:"word",en:"proud",ja:"誇りに思う"},
{id:"w655",type:"word",en:"embarrassed",ja:"恥ずかしい"},
{id:"w656",type:"word",en:"comfortable",ja:"快適な"},
{id:"w657",type:"word",en:"careful",ja:"注意深い"},
{id:"w658",type:"word",en:"creative",ja:"創造的な"},
{id:"w659",type:"word",en:"flexible",ja:"柔軟な"},
{id:"w660",type:"word",en:"familiar",ja:"親しみやすい / よく知っている"},
{id:"w661",type:"word",en:"professional",ja:"プロの / 専門的な"},
{id:"w662",type:"word",en:"appropriate",ja:"適切な"},
{id:"w663",type:"word",en:"successful",ja:"成功した"},
{id:"w664",type:"word",en:"typical",ja:"典型的な"},
{id:"w665",type:"word",en:"necessary",ja:"必要な"},
{id:"w666",type:"word",en:"helpful",ja:"役立つ"},
{id:"w667",type:"word",en:"harmful",ja:"有害な"},
{id:"w668",type:"word",en:"powerful",ja:"力強い"},
{id:"w669",type:"word",en:"useful",ja:"役に立つ"},
{id:"w670",type:"word",en:"direct",ja:"直接の / 直接に"},
{id:"w671",type:"word",en:"recent",ja:"最近の"},
{id:"w672",type:"word",en:"official",ja:"公式の / 公式者"},
{id:"w673",type:"word",en:"original",ja:"オリジナルの"},
{id:"w674",type:"word",en:"basic",ja:"基本的な"},
{id:"w675",type:"word",en:"final",ja:"最終的な"},
{id:"w676",type:"word",en:"specific",ja:"具体的な"},
{id:"w677",type:"word",en:"main",ja:"主要な"},
{id:"w678",type:"word",en:"general",ja:"一般的な"},
{id:"w679",type:"word",en:"particular",ja:"特定の"},
{id:"w680",type:"word",en:"certain",ja:"確かな / ある〜"},
{id:"w681",type:"word",en:"several",ja:"いくつかの"},
{id:"w682",type:"word",en:"single",ja:"一つの / 独身の"},
{id:"w683",type:"word",en:"simple",ja:"簡単な / シンプルな"},
{id:"w684",type:"word",en:"complex",ja:"複雑な"},
{id:"w685",type:"word",en:"deep",ja:"深い"},
{id:"w686",type:"word",en:"wide",ja:"広い"},
{id:"w687",type:"word",en:"fast",ja:"速い / 速く"},
{id:"w688",type:"word",en:"slow",ja:"遅い / ゆっくり"},
{id:"w689",type:"word",en:"bright",ja:"明るい"},
{id:"w690",type:"word",en:"dark",ja:"暗い"},
{id:"w691",type:"word",en:"quiet",ja:"静かな"},
{id:"w692",type:"word",en:"loud",ja:"うるさい"},
{id:"w693",type:"word",en:"sweet",ja:"甘い / かわいい"},
{id:"w694",type:"word",en:"bitter",ja:"苦い"},
{id:"w695",type:"word",en:"soft",ja:"柔らかい"},
{id:"w696",type:"word",en:"clean",ja:"きれいな / 清潔な"},
{id:"w697",type:"word",en:"dirty",ja:"汚い"},
{id:"w698",type:"word",en:"safe",ja:"安全な"},
{id:"w699",type:"word",en:"dangerous",ja:"危険な"},
{id:"w700",type:"word",en:"beautiful",ja:"美しい"},
// ── CHUNKS (type:"chunk") ── 中学生がよく使うフレーズ300 ──
// あいさつ
{id:"c001",type:"chunk",en:"Hey!",ja:"やあ！"},
{id:"c002",type:"chunk",en:"Hi there!",ja:"こんにちは！"},
{id:"c003",type:"chunk",en:"What's up?",ja:"調子どう？"},
{id:"c004",type:"chunk",en:"How's it going?",ja:"最近どう？"},
{id:"c005",type:"chunk",en:"Good morning!",ja:"おはようございます！"},
{id:"c006",type:"chunk",en:"Good afternoon!",ja:"こんにちは！（昼）"},
{id:"c007",type:"chunk",en:"Good night!",ja:"おやすみなさい！"},
{id:"c008",type:"chunk",en:"Nice to meet you.",ja:"はじめまして。"},
{id:"c009",type:"chunk",en:"See you later!",ja:"またね！"},
{id:"c010",type:"chunk",en:"See you tomorrow!",ja:"また明日！"},
{id:"c011",type:"chunk",en:"Bye!",ja:"さようなら！"},
{id:"c012",type:"chunk",en:"Take care!",ja:"気をつけてね！"},
{id:"c013",type:"chunk",en:"Have a good day!",ja:"いい一日を！"},
{id:"c014",type:"chunk",en:"Long time no see!",ja:"久しぶり！"},
{id:"c015",type:"chunk",en:"Nice to see you!",ja:"会えてうれしい！"},
// 返答・調子
{id:"c016",type:"chunk",en:"I'm good, thanks.",ja:"元気だよ、ありがとう。"},
{id:"c017",type:"chunk",en:"I'm doing great!",ja:"最高だよ！"},
{id:"c018",type:"chunk",en:"Not bad.",ja:"悪くないよ。"},
// 返答・感情
{id:"c019",type:"chunk",en:"I'm tired.",ja:"疲れた。"},
{id:"c020",type:"chunk",en:"I'm so hungry.",ja:"めちゃくちゃお腹すいた。"},
{id:"c021",type:"chunk",en:"I'm bored.",ja:"退屈だな。"},
{id:"c022",type:"chunk",en:"I'm nervous.",ja:"緊張してる。"},
{id:"c023",type:"chunk",en:"I'm excited!",ja:"ワクワクする！"},
{id:"c024",type:"chunk",en:"I'm scared.",ja:"怖い。"},
{id:"c025",type:"chunk",en:"I'm happy.",ja:"うれしい。"},
{id:"c026",type:"chunk",en:"I'm sad.",ja:"悲しい。"},
{id:"c027",type:"chunk",en:"I'm angry.",ja:"怒ってる。"},
{id:"c028",type:"chunk",en:"I'm embarrassed.",ja:"恥ずかしい。"},
{id:"c029",type:"chunk",en:"I'm surprised.",ja:"びっくりした。"},
{id:"c030",type:"chunk",en:"I'm proud of you.",ja:"あなたのことが誇らしい。"},
// 同意・不同意
{id:"c031",type:"chunk",en:"Me too!",ja:"私もそう！"},
{id:"c032",type:"chunk",en:"Same here.",ja:"私も同じ。"},
{id:"c033",type:"chunk",en:"I know, right?",ja:"だよね？"},
{id:"c034",type:"chunk",en:"Totally!",ja:"まったくそうだよ！"},
{id:"c035",type:"chunk",en:"I agree.",ja:"同意するよ。"},
{id:"c036",type:"chunk",en:"I don't think so.",ja:"そうは思わないな。"},
{id:"c037",type:"chunk",en:"Not really.",ja:"そうでもないかな。"},
{id:"c038",type:"chunk",en:"No way!",ja:"まさか！ / 嘘でしょ！"},
{id:"c039",type:"chunk",en:"That's not fair.",ja:"それはずるい。"},
{id:"c040",type:"chunk",en:"Whatever.",ja:"どうでもいい。"},
// 驚き・反応
{id:"c041",type:"chunk",en:"Oh my gosh!",ja:"えー！ / うそ！"},
{id:"c042",type:"chunk",en:"Are you serious?",ja:"本気で言ってるの？"},
{id:"c043",type:"chunk",en:"No way!",ja:"ありえない！"},
{id:"c044",type:"chunk",en:"That's crazy!",ja:"すごい！ / 信じられない！"},
{id:"c045",type:"chunk",en:"Wow, really?",ja:"えー、本当に？"},
{id:"c046",type:"chunk",en:"Are you kidding me?",ja:"冗談でしょ？"},
{id:"c047",type:"chunk",en:"I can't believe it!",ja:"信じられない！"},
{id:"c048",type:"chunk",en:"That's so cool!",ja:"それ超かっこいい！"},
{id:"c049",type:"chunk",en:"That's awesome!",ja:"最高だね！"},
{id:"c050",type:"chunk",en:"That's terrible!",ja:"最悪！"},
{id:"c051",type:"chunk",en:"That's funny!",ja:"面白い！"},
{id:"c052",type:"chunk",en:"That's weird.",ja:"それ変だね。"},
{id:"c053",type:"chunk",en:"That's too bad.",ja:"それは残念だね。"},
{id:"c054",type:"chunk",en:"I had no idea.",ja:"全然知らなかった。"},
// 学校・授業
{id:"c055",type:"chunk",en:"Can I go to the bathroom?",ja:"トイレに行ってもいいですか？"},
{id:"c056",type:"chunk",en:"I don't understand.",ja:"わかりません。"},
{id:"c057",type:"chunk",en:"Can you say that again?",ja:"もう一度言ってもらえますか？"},
{id:"c058",type:"chunk",en:"What page are we on?",ja:"今何ページですか？"},
{id:"c059",type:"chunk",en:"I forgot my homework.",ja:"宿題を忘れました。"},
{id:"c060",type:"chunk",en:"Can I borrow a pencil?",ja:"鉛筆を借りてもいいですか？"},
{id:"c061",type:"chunk",en:"When is this due?",ja:"これはいつまでですか？"},
{id:"c062",type:"chunk",en:"Is this going to be on the test?",ja:"これはテストに出ますか？"},
{id:"c063",type:"chunk",en:"I got it!",ja:"わかった！"},
{id:"c064",type:"chunk",en:"I have no idea.",ja:"全然わからない。"},
{id:"c065",type:"chunk",en:"Can you help me?",ja:"助けてもらえますか？"},
{id:"c066",type:"chunk",en:"Can we work in groups?",ja:"グループで作業してもいいですか？"},
{id:"c067",type:"chunk",en:"I need more time.",ja:"もう少し時間が必要です。"},
{id:"c068",type:"chunk",en:"I'm done.",ja:"終わった。"},
{id:"c069",type:"chunk",en:"I'm not done yet.",ja:"まだ終わっていません。"},
{id:"c070",type:"chunk",en:"This is hard.",ja:"これは難しい。"},
{id:"c071",type:"chunk",en:"This is easy.",ja:"これは簡単。"},
{id:"c072",type:"chunk",en:"I made a mistake.",ja:"ミスしてしまった。"},
{id:"c073",type:"chunk",en:"Let me try again.",ja:"もう一度やらせて。"},
{id:"c074",type:"chunk",en:"I think I understand.",ja:"たぶん理解できたと思う。"},
// 友達との会話
{id:"c075",type:"chunk",en:"What are you doing?",ja:"何してるの？"},
{id:"c076",type:"chunk",en:"Where are you going?",ja:"どこに行くの？"},
{id:"c077",type:"chunk",en:"Can you come with me?",ja:"一緒に来てくれる？"},
{id:"c078",type:"chunk",en:"Let's hang out.",ja:"遊ぼうよ。"},
{id:"c079",type:"chunk",en:"Are you free tomorrow?",ja:"明日暇？"},
{id:"c080",type:"chunk",en:"What do you want to do?",ja:"何がしたい？"},
{id:"c081",type:"chunk",en:"It's up to you.",ja:"あなた次第だよ。"},
{id:"c082",type:"chunk",en:"I don't care.",ja:"どっちでもいいよ。"},
{id:"c083",type:"chunk",en:"Sounds fun!",ja:"楽しそう！"},
{id:"c084",type:"chunk",en:"Sounds good!",ja:"いいね！"},
{id:"c085",type:"chunk",en:"I can't. I'm busy.",ja:"無理。忙しいんだ。"},
{id:"c086",type:"chunk",en:"Maybe next time.",ja:"また今度ね。"},
{id:"c087",type:"chunk",en:"Let's go!",ja:"行こう！"},
{id:"c088",type:"chunk",en:"Wait for me!",ja:"待ってよ！"},
{id:"c089",type:"chunk",en:"Hurry up!",ja:"急いで！"},
{id:"c090",type:"chunk",en:"Be careful!",ja:"気をつけて！"},
// 好き・嫌い
{id:"c091",type:"chunk",en:"I love it!",ja:"大好き！"},
{id:"c092",type:"chunk",en:"I like it.",ja:"好きだよ。"},
{id:"c093",type:"chunk",en:"I don't like it.",ja:"好きじゃない。"},
{id:"c094",type:"chunk",en:"I hate it.",ja:"嫌いだ。"},
{id:"c095",type:"chunk",en:"It's my favorite!",ja:"お気に入り！"},
{id:"c096",type:"chunk",en:"I'm not into it.",ja:"ハマってないな。"},
{id:"c097",type:"chunk",en:"I'm really into it.",ja:"すごくハマってる。"},
{id:"c098",type:"chunk",en:"What's your favorite?",ja:"お気に入りは何？"},
{id:"c099",type:"chunk",en:"Do you like it?",ja:"好き？"},
{id:"c100",type:"chunk",en:"It's okay.",ja:"まあまあかな。"},
{id:"c101",type:"chunk",en:"Not my thing.",ja:"私には合わないな。"},
{id:"c102",type:"chunk",en:"I'm obsessed with it.",ja:"めちゃくちゃ好き。"},
// お礼・謝り
{id:"c103",type:"chunk",en:"Thank you!",ja:"ありがとう！"},
{id:"c104",type:"chunk",en:"Thanks a lot!",ja:"本当にありがとう！"},
{id:"c105",type:"chunk",en:"You're welcome.",ja:"どういたしまして。"},
{id:"c106",type:"chunk",en:"No problem.",ja:"問題ないよ。"},
{id:"c107",type:"chunk",en:"Don't worry about it.",ja:"気にしないで。"},
{id:"c108",type:"chunk",en:"No worries.",ja:"大丈夫だよ。"},
{id:"c109",type:"chunk",en:"I'm sorry.",ja:"ごめんなさい。"},
{id:"c110",type:"chunk",en:"My bad.",ja:"私のミス。"},
{id:"c111",type:"chunk",en:"I'm so sorry.",ja:"本当にごめん。"},
{id:"c112",type:"chunk",en:"That's okay.",ja:"大丈夫だよ。"},
{id:"c113",type:"chunk",en:"It's fine.",ja:"いいよ。"},
{id:"c114",type:"chunk",en:"Forget it.",ja:"気にしないで。"},
// 意見・考え
{id:"c115",type:"chunk",en:"I think so.",ja:"そう思うよ。"},
{id:"c116",type:"chunk",en:"I don't think so.",ja:"そうは思わない。"},
{id:"c117",type:"chunk",en:"I think it's great.",ja:"すごいと思う。"},
{id:"c118",type:"chunk",en:"I think it's boring.",ja:"退屈だと思う。"},
{id:"c119",type:"chunk",en:"What do you think?",ja:"どう思う？"},
{id:"c120",type:"chunk",en:"In my opinion,",ja:"私の意見では、"},
{id:"c121",type:"chunk",en:"To be honest,",ja:"正直に言うと、"},
{id:"c122",type:"chunk",en:"Actually,",ja:"実は、"},
{id:"c123",type:"chunk",en:"I mean,",ja:"つまり、"},
{id:"c124",type:"chunk",en:"You know,",ja:"ほら、（つなぎ言葉）"},
{id:"c125",type:"chunk",en:"kind of",ja:"ちょっと〜みたいな"},
{id:"c126",type:"chunk",en:"sort of",ja:"なんか〜みたいな"},
{id:"c127",type:"chunk",en:"Honestly,",ja:"正直、"},
{id:"c128",type:"chunk",en:"I guess so.",ja:"たぶんそうかな。"},
{id:"c129",type:"chunk",en:"I'm not sure.",ja:"よくわからない。"},
{id:"c130",type:"chunk",en:"Maybe.",ja:"たぶんね。"},
// 食べ物・食事
{id:"c131",type:"chunk",en:"I'm hungry.",ja:"お腹すいた。"},
{id:"c132",type:"chunk",en:"I'm full.",ja:"お腹いっぱい。"},
{id:"c133",type:"chunk",en:"That looks delicious!",ja:"おいしそう！"},
{id:"c134",type:"chunk",en:"That was so good!",ja:"めちゃくちゃおいしかった！"},
{id:"c135",type:"chunk",en:"I don't like vegetables.",ja:"野菜が好きじゃない。"},
{id:"c136",type:"chunk",en:"Can I have some more?",ja:"もう少しもらえる？"},
{id:"c137",type:"chunk",en:"What do you want to eat?",ja:"何食べたい？"},
{id:"c138",type:"chunk",en:"Let's get something to eat.",ja:"何か食べに行こう。"},
{id:"c139",type:"chunk",en:"I'll have this, please.",ja:"これをください。"},
{id:"c140",type:"chunk",en:"Can I try some?",ja:"少し食べてもいい？"},
// スポーツ・趣味
{id:"c141",type:"chunk",en:"Do you play sports?",ja:"スポーツはするの？"},
{id:"c142",type:"chunk",en:"What's your hobby?",ja:"趣味は何？"},
{id:"c143",type:"chunk",en:"I play soccer.",ja:"サッカーをやってるよ。"},
{id:"c144",type:"chunk",en:"I love watching movies.",ja:"映画を見るのが大好き。"},
{id:"c145",type:"chunk",en:"I listen to music all the time.",ja:"いつも音楽を聴いてる。"},
{id:"c146",type:"chunk",en:"I play video games.",ja:"ゲームをするよ。"},
{id:"c147",type:"chunk",en:"Let's play!",ja:"遊ぼう！"},
{id:"c148",type:"chunk",en:"I'm on the team.",ja:"チームに入ってるよ。"},
{id:"c149",type:"chunk",en:"We won!",ja:"勝ったよ！"},
{id:"c150",type:"chunk",en:"We lost.",ja:"負けた。"},
{id:"c151",type:"chunk",en:"Good game!",ja:"いい試合だった！"},
{id:"c152",type:"chunk",en:"Practice makes perfect.",ja:"練習あるのみ。"},
// 励まし
{id:"c153",type:"chunk",en:"You can do it!",ja:"できるよ！"},
{id:"c154",type:"chunk",en:"Don't give up!",ja:"あきらめないで！"},
{id:"c155",type:"chunk",en:"Keep going!",ja:"続けて！"},
{id:"c156",type:"chunk",en:"You're doing great!",ja:"すごくうまくやってるよ！"},
{id:"c157",type:"chunk",en:"Good job!",ja:"よくやった！"},
{id:"c158",type:"chunk",en:"Well done!",ja:"よくできました！"},
{id:"c159",type:"chunk",en:"I'm proud of you.",ja:"誇りに思うよ。"},
{id:"c160",type:"chunk",en:"You're awesome!",ja:"あなたは最高！"},
{id:"c161",type:"chunk",en:"Nice try.",ja:"惜しかったね。"},
{id:"c162",type:"chunk",en:"Keep it up!",ja:"その調子で！"},
{id:"c163",type:"chunk",en:"Hang in there!",ja:"頑張れ！"},
{id:"c164",type:"chunk",en:"Go for it!",ja:"やってみよう！"},
// 日常のひとこと
{id:"c165",type:"chunk",en:"I'm home!",ja:"ただいま！"},
{id:"c166",type:"chunk",en:"Welcome home!",ja:"おかえり！"},
{id:"c167",type:"chunk",en:"Let's go!",ja:"行こう！"},
{id:"c168",type:"chunk",en:"I'm ready.",ja:"準備できた。"},
{id:"c169",type:"chunk",en:"Wait a minute.",ja:"ちょっと待って。"},
{id:"c170",type:"chunk",en:"Just a second.",ja:"少し待って。"},
{id:"c171",type:"chunk",en:"I'm coming!",ja:"今行くよ！"},
{id:"c172",type:"chunk",en:"Here you go.",ja:"はい、どうぞ。"},
{id:"c173",type:"chunk",en:"After you.",ja:"お先にどうぞ。"},
{id:"c174",type:"chunk",en:"Be right back.",ja:"すぐ戻るよ。"},
{id:"c175",type:"chunk",en:"I'll be right there.",ja:"すぐそっちに行くよ。"},
{id:"c176",type:"chunk",en:"I'm on my way.",ja:"今向かってるよ。"},
{id:"c177",type:"chunk",en:"I'm running late.",ja:"遅れそう。"},
{id:"c178",type:"chunk",en:"I'm almost there.",ja:"もうすぐ着くよ。"},
{id:"c179",type:"chunk",en:"Take your time.",ja:"ゆっくりどうぞ。"},
{id:"c180",type:"chunk",en:"No rush.",ja:"急がなくていいよ。"},
// 質問する
{id:"c181",type:"chunk",en:"What's your name?",ja:"名前は何ですか？"},
{id:"c182",type:"chunk",en:"How old are you?",ja:"何歳ですか？"},
{id:"c183",type:"chunk",en:"Where are you from?",ja:"どこから来たの？"},
{id:"c184",type:"chunk",en:"What grade are you in?",ja:"何年生ですか？"},
{id:"c185",type:"chunk",en:"Do you have a pet?",ja:"ペットはいる？"},
{id:"c186",type:"chunk",en:"What's your favorite subject?",ja:"好きな科目は何？"},
{id:"c187",type:"chunk",en:"What did you do last weekend?",ja:"先週末は何したの？"},
{id:"c188",type:"chunk",en:"What are you going to do?",ja:"何をするつもりなの？"},
{id:"c189",type:"chunk",en:"How was your day?",ja:"今日はどうだった？"},
{id:"c190",type:"chunk",en:"Did you watch the game?",ja:"試合見た？"},
// SNS・スマホ
{id:"c191",type:"chunk",en:"Check this out!",ja:"これ見て！"},
{id:"c192",type:"chunk",en:"Did you see that video?",ja:"あの動画見た？"},
{id:"c193",type:"chunk",en:"That's so funny!",ja:"めちゃくちゃ笑える！"},
{id:"c194",type:"chunk",en:"Send me the link.",ja:"リンク送って。"},
{id:"c195",type:"chunk",en:"Follow me.",ja:"フォローしてね。"},
{id:"c196",type:"chunk",en:"That went viral.",ja:"それバズったね。"},
{id:"c197",type:"chunk",en:"I saw it on TikTok.",ja:"TikTokで見た。"},
{id:"c198",type:"chunk",en:"Did you see his post?",ja:"彼の投稿見た？"},
{id:"c199",type:"chunk",en:"My phone died.",ja:"スマホのバッテリーが切れた。"},
{id:"c200",type:"chunk",en:"Can I borrow your charger?",ja:"充電器貸してくれる？"},
// 体調
{id:"c201",type:"chunk",en:"I don't feel well.",ja:"体調が良くない。"},
{id:"c202",type:"chunk",en:"I have a cold.",ja:"風邪をひいた。"},
{id:"c203",type:"chunk",en:"I have a headache.",ja:"頭が痛い。"},
{id:"c204",type:"chunk",en:"My stomach hurts.",ja:"お腹が痛い。"},
{id:"c205",type:"chunk",en:"I'm feeling better now.",ja:"今は良くなった。"},
{id:"c206",type:"chunk",en:"Get well soon!",ja:"早く良くなってね！"},
{id:"c207",type:"chunk",en:"Are you okay?",ja:"大丈夫？"},
{id:"c208",type:"chunk",en:"Take care of yourself.",ja:"体に気をつけてね。"},
{id:"c209",type:"chunk",en:"Get some rest.",ja:"休んでね。"},
{id:"c210",type:"chunk",en:"I'm so sleepy.",ja:"眠い。"},
// 時間・予定
{id:"c211",type:"chunk",en:"What time is it?",ja:"今何時？"},
{id:"c212",type:"chunk",en:"I'm late!",ja:"遅刻だ！"},
{id:"c213",type:"chunk",en:"I have practice today.",ja:"今日練習がある。"},
{id:"c214",type:"chunk",en:"I have a lot of homework.",ja:"宿題がたくさんある。"},
{id:"c215",type:"chunk",en:"I have an exam tomorrow.",ja:"明日テストがある。"},
{id:"c216",type:"chunk",en:"I stayed up late.",ja:"夜更かしした。"},
{id:"c217",type:"chunk",en:"I woke up early.",ja:"早起きした。"},
{id:"c218",type:"chunk",en:"Let's meet at three.",ja:"3時に会おう。"},
{id:"c219",type:"chunk",en:"I'll be there in ten minutes.",ja:"10分で着くよ。"},
{id:"c220",type:"chunk",en:"right now",ja:"今すぐ"},
{id:"c221",type:"chunk",en:"later",ja:"後で"},
{id:"c222",type:"chunk",en:"all the time",ja:"いつも / しょっちゅう"},
{id:"c223",type:"chunk",en:"once in a while",ja:"たまに"},
{id:"c224",type:"chunk",en:"these days",ja:"最近"},
// 確認・聞き取り
{id:"c225",type:"chunk",en:"What did you say?",ja:"何て言ったの？"},
{id:"c226",type:"chunk",en:"I didn't hear you.",ja:"聞こえなかった。"},
{id:"c227",type:"chunk",en:"Can you speak more slowly?",ja:"もっとゆっくり話してもらえる？"},
{id:"c228",type:"chunk",en:"What do you mean?",ja:"どういう意味？"},
{id:"c229",type:"chunk",en:"Could you repeat that?",ja:"もう一度言ってもらえる？"},
{id:"c230",type:"chunk",en:"I didn't catch that.",ja:"聞き取れなかった。"},
{id:"c231",type:"chunk",en:"Got it!",ja:"わかった！"},
{id:"c232",type:"chunk",en:"Makes sense.",ja:"なるほど。"},
{id:"c233",type:"chunk",en:"I see.",ja:"そうか。"},
{id:"c234",type:"chunk",en:"Really?",ja:"本当に？"},
// 提案・誘い
{id:"c235",type:"chunk",en:"How about this?",ja:"これはどう？"},
{id:"c236",type:"chunk",en:"What if we try this?",ja:"これを試してみたら？"},
{id:"c237",type:"chunk",en:"Why don't we go there?",ja:"そこに行かない？"},
{id:"c238",type:"chunk",en:"Let's try it.",ja:"やってみよう。"},
{id:"c239",type:"chunk",en:"Give it a try!",ja:"試してみて！"},
{id:"c240",type:"chunk",en:"Count me in!",ja:"私も参加する！"},
{id:"c241",type:"chunk",en:"I'm down.",ja:"いいよ。（口語で同意）"},
{id:"c242",type:"chunk",en:"I'm in!",ja:"参加する！"},
{id:"c243",type:"chunk",en:"That's a great idea!",ja:"それ良いアイデア！"},
{id:"c244",type:"chunk",en:"Not a bad idea.",ja:"悪くないね。"},
// 口語表現・フィラー
{id:"c245",type:"chunk",en:"Like,",ja:"なんか、（つなぎ言葉）"},
{id:"c246",type:"chunk",en:"Literally,",ja:"ほんとに（強調）"},
{id:"c247",type:"chunk",en:"Basically,",ja:"基本的に、"},
{id:"c248",type:"chunk",en:"Anyway,",ja:"とにかく、"},
{id:"c249",type:"chunk",en:"So yeah.",ja:"まあ、そういうことで。"},
{id:"c250",type:"chunk",en:"By the way,",ja:"ところで、"},
{id:"c251",type:"chunk",en:"Guess what?",ja:"なんだと思う？"},
{id:"c252",type:"chunk",en:"You know what?",ja:"ねえ聞いて？"},
{id:"c253",type:"chunk",en:"For real?",ja:"マジで？"},
{id:"c254",type:"chunk",en:"For real!",ja:"マジだよ！"},
// 学校・クラブ
{id:"c255",type:"chunk",en:"I joined the club.",ja:"部活に入ったよ。"},
{id:"c256",type:"chunk",en:"We have a field trip.",ja:"遠足がある。"},
{id:"c257",type:"chunk",en:"I aced the test!",ja:"テストで満点とった！"},
{id:"c258",type:"chunk",en:"I failed the test.",ja:"テストに落ちた。"},
{id:"c259",type:"chunk",en:"The teacher is strict.",ja:"先生が厳しい。"},
{id:"c260",type:"chunk",en:"Class is over.",ja:"授業が終わった。"},
{id:"c261",type:"chunk",en:"School is out!",ja:"学校が終わった！"},
{id:"c262",type:"chunk",en:"I have to study.",ja:"勉強しなきゃ。"},
{id:"c263",type:"chunk",en:"I can't wait for the break.",ja:"休み時間が待ち遠しい。"},
{id:"c264",type:"chunk",en:"Can I copy your notes?",ja:"ノートを見せてもらえる？"},
// 家族・日常
{id:"c265",type:"chunk",en:"My mom said no.",ja:"お母さんがダメって言った。"},
{id:"c266",type:"chunk",en:"I have chores to do.",ja:"家の手伝いがある。"},
{id:"c267",type:"chunk",en:"I have a curfew.",ja:"門限がある。"},
{id:"c268",type:"chunk",en:"Can I go out?",ja:"出かけていい？"},
{id:"c269",type:"chunk",en:"I'm staying home today.",ja:"今日は家にいるよ。"},
{id:"c270",type:"chunk",en:"My family is going on a trip.",ja:"家族で旅行に行くよ。"},
// ゲーム・エンタメ
{id:"c271",type:"chunk",en:"Let's play together.",ja:"一緒にやろう。"},
{id:"c272",type:"chunk",en:"I leveled up!",ja:"レベルアップした！"},
{id:"c273",type:"chunk",en:"Game over.",ja:"ゲームオーバー。"},
{id:"c274",type:"chunk",en:"I beat the boss!",ja:"ボスを倒した！"},
{id:"c275",type:"chunk",en:"Have you played this game?",ja:"このゲームやったことある？"},
{id:"c276",type:"chunk",en:"What are you watching?",ja:"何見てるの？"},
{id:"c277",type:"chunk",en:"Have you seen this movie?",ja:"この映画見た？"},
{id:"c278",type:"chunk",en:"It's so good!",ja:"めちゃくちゃいい！"},
{id:"c279",type:"chunk",en:"I recommend it!",ja:"おすすめだよ！"},
{id:"c280",type:"chunk",en:"Spoiler alert!",ja:"ネタバレ注意！"},
// 慣用表現（中学生向け）
{id:"c281",type:"chunk",en:"Break a leg!",ja:"頑張って！（試験・舞台前に）"},
{id:"c282",type:"chunk",en:"No pain, no gain.",ja:"苦あれば楽あり。"},
{id:"c283",type:"chunk",en:"It's a piece of cake.",ja:"朝飯前だよ。（超簡単）"},
{id:"c284",type:"chunk",en:"under the weather",ja:"体調が悪い"},
{id:"c285",type:"chunk",en:"hit the books",ja:"勉強する"},
{id:"c286",type:"chunk",en:"bite the bullet",ja:"歯を食いしばる"},
{id:"c287",type:"chunk",en:"You got this!",ja:"絶対できる！"},
{id:"c288",type:"chunk",en:"I'm all ears.",ja:"聞いてるよ。（話して）"},
{id:"c289",type:"chunk",en:"That's on me.",ja:"それは私のせい。"},
{id:"c290",type:"chunk",en:"No biggie.",ja:"大したことじゃないよ。"},
// まとめ・締め
{id:"c291",type:"chunk",en:"That's it!",ja:"それだけ！ / 終わり！"},
{id:"c292",type:"chunk",en:"That's all.",ja:"以上です。"},
{id:"c293",type:"chunk",en:"I gotta go.",ja:"もう行かなきゃ。"},
{id:"c294",type:"chunk",en:"Talk to you later.",ja:"また話そう。"},
{id:"c295",type:"chunk",en:"Text me!",ja:"メッセージしてね！"},
{id:"c296",type:"chunk",en:"Call me!",ja:"電話してね！"},
{id:"c297",type:"chunk",en:"Miss you!",ja:"会いたいよ！"},
{id:"c298",type:"chunk",en:"Take care!",ja:"気をつけてね！"},
{id:"c299",type:"chunk",en:"See you around!",ja:"またそのうちね！"},
{id:"c300",type:"chunk",en:"Have fun!",ja:"楽しんでね！"},
];
