// ============================================================
// DATA: 700 chunks — native daily-conversation phrases
// ============================================================
window.ITEMS = [
// ── CHUNKS (type:"chunk") ── 700 native daily conversation phrases ──
// あいさつ
{id:"c001",type:"chunk",en:"Hey!",ja:"やあ！"},
{id:"c002",type:"chunk",en:"Hi there!",ja:"こんにちは！"},
{id:"c003",type:"chunk",en:"What's up?",ja:"調子どう？"},
{id:"c004",type:"chunk",en:"How's it going?",ja:"最近どう？"},
{id:"c005",type:"chunk",en:"How are you doing?",ja:"元気にしてる？"},
{id:"c006",type:"chunk",en:"How have you been?",ja:"最近どうしてた？"},
{id:"c007",type:"chunk",en:"Long time no see!",ja:"久しぶり！"},
{id:"c008",type:"chunk",en:"It's been a while.",ja:"しばらくぶりだね。"},
{id:"c009",type:"chunk",en:"Good to see you!",ja:"会えてうれしいよ！"},
{id:"c010",type:"chunk",en:"Good morning!",ja:"おはよう！"},
{id:"c011",type:"chunk",en:"Good afternoon!",ja:"こんにちは！（昼）"},
{id:"c012",type:"chunk",en:"Good evening!",ja:"こんばんは！"},
// 別れ
{id:"c013",type:"chunk",en:"See you later!",ja:"またね！"},
{id:"c014",type:"chunk",en:"See you soon!",ja:"また近いうちに！"},
{id:"c015",type:"chunk",en:"Take care!",ja:"気をつけてね！"},
{id:"c016",type:"chunk",en:"Take it easy.",ja:"気楽にね。"},
{id:"c017",type:"chunk",en:"Catch you later!",ja:"あとでね！"},
{id:"c018",type:"chunk",en:"Have a good one!",ja:"良い一日を！"},
{id:"c019",type:"chunk",en:"Have a good day!",ja:"いい一日を！"},
{id:"c020",type:"chunk",en:"Have a good night!",ja:"おやすみ！"},
{id:"c021",type:"chunk",en:"Have a good weekend!",ja:"良い週末を！"},
{id:"c022",type:"chunk",en:"Drive safe.",ja:"運転気をつけてね。"},
{id:"c023",type:"chunk",en:"Safe travels!",ja:"道中気をつけて！"},
{id:"c024",type:"chunk",en:"Talk to you later.",ja:"また話そう。"},
// 「元気？」への返事
{id:"c025",type:"chunk",en:"I'm good, thanks.",ja:"元気だよ、ありがとう。"},
{id:"c026",type:"chunk",en:"Pretty good.",ja:"まあまあいいよ。"},
{id:"c027",type:"chunk",en:"Not bad.",ja:"悪くないよ。"},
{id:"c028",type:"chunk",en:"Can't complain.",ja:"文句は言えないね。"},
{id:"c029",type:"chunk",en:"Same as usual.",ja:"いつも通りだよ。"},
{id:"c030",type:"chunk",en:"Hanging in there.",ja:"なんとかやってるよ。"},
{id:"c031",type:"chunk",en:"I'm doing great!",ja:"絶好調！"},
{id:"c032",type:"chunk",en:"Could be better.",ja:"もう少しかな。"},
{id:"c033",type:"chunk",en:"I've been better.",ja:"今はちょっとパッとしない。"},
{id:"c034",type:"chunk",en:"Same old, same old.",ja:"いつもと同じだよ。"},
{id:"c035",type:"chunk",en:"Busy as always.",ja:"いつも通り忙しいよ。"},
{id:"c036",type:"chunk",en:"Going well, thanks!",ja:"順調だよ、ありがとう！"},
// 感情
{id:"c037",type:"chunk",en:"I'm exhausted.",ja:"へとへとだ。"},
{id:"c038",type:"chunk",en:"I'm wiped out.",ja:"クタクタだ。"},
{id:"c039",type:"chunk",en:"I'm beat.",ja:"疲れた。"},
{id:"c040",type:"chunk",en:"I'm starving.",ja:"お腹ペコペコ。"},
{id:"c041",type:"chunk",en:"I'm full.",ja:"お腹いっぱい。"},
{id:"c042",type:"chunk",en:"I'm stuffed.",ja:"満腹だ。"},
{id:"c043",type:"chunk",en:"I'm thirsty.",ja:"喉が渇いた。"},
{id:"c044",type:"chunk",en:"I'm bored.",ja:"退屈だ。"},
{id:"c045",type:"chunk",en:"I'm nervous.",ja:"緊張してる。"},
{id:"c046",type:"chunk",en:"I'm so excited!",ja:"すごくワクワクする！"},
{id:"c047",type:"chunk",en:"I can't wait!",ja:"待ちきれない！"},
{id:"c048",type:"chunk",en:"I'm scared.",ja:"怖い。"},
{id:"c049",type:"chunk",en:"I'm freaking out.",ja:"パニックだ。"},
{id:"c050",type:"chunk",en:"I'm stressed out.",ja:"ストレスでまいってる。"},
{id:"c051",type:"chunk",en:"I'm overwhelmed.",ja:"いっぱいいっぱいだ。"},
{id:"c052",type:"chunk",en:"I'm so happy right now.",ja:"今めちゃくちゃ幸せ。"},
{id:"c053",type:"chunk",en:"I'm thrilled.",ja:"めちゃ嬉しい。"},
{id:"c054",type:"chunk",en:"I'm a bit down.",ja:"ちょっと落ち込んでる。"},
{id:"c055",type:"chunk",en:"I'm bummed.",ja:"がっかりした。"},
{id:"c056",type:"chunk",en:"I'm annoyed.",ja:"イライラしてる。"},
{id:"c057",type:"chunk",en:"I'm furious.",ja:"激怒してる。"},
{id:"c058",type:"chunk",en:"I'm in a good mood.",ja:"気分がいい。"},
{id:"c059",type:"chunk",en:"I'm in a bad mood.",ja:"機嫌が悪い。"},
{id:"c060",type:"chunk",en:"I'm feeling off today.",ja:"今日はなんか調子が変。"},
{id:"c061",type:"chunk",en:"I'm not myself today.",ja:"今日はいつもの自分じゃない。"},
{id:"c062",type:"chunk",en:"I'm dead tired.",ja:"死ぬほど疲れた。"},
{id:"c063",type:"chunk",en:"I'm worn out.",ja:"消耗しきった。"},
{id:"c064",type:"chunk",en:"I'm relieved.",ja:"ホッとした。"},
{id:"c065",type:"chunk",en:"I'm fed up.",ja:"もううんざりだ。"},
{id:"c066",type:"chunk",en:"I'm sick of it.",ja:"もう飽き飽きだ。"},
// 同意
{id:"c067",type:"chunk",en:"Totally.",ja:"まったくその通り。"},
{id:"c068",type:"chunk",en:"Absolutely.",ja:"絶対そう。"},
{id:"c069",type:"chunk",en:"For sure.",ja:"確かに。"},
{id:"c070",type:"chunk",en:"Definitely.",ja:"間違いなく。"},
{id:"c071",type:"chunk",en:"I agree.",ja:"同意するよ。"},
{id:"c072",type:"chunk",en:"I couldn't agree more.",ja:"これ以上ないくらい同意。"},
{id:"c073",type:"chunk",en:"You're right.",ja:"その通り。"},
{id:"c074",type:"chunk",en:"That's true.",ja:"本当だね。"},
{id:"c075",type:"chunk",en:"I know, right?",ja:"だよね？"},
{id:"c076",type:"chunk",en:"Tell me about it.",ja:"わかる、それな。"},
{id:"c077",type:"chunk",en:"Same here.",ja:"私も同じ。"},
{id:"c078",type:"chunk",en:"Exactly.",ja:"まさにそう。"},
{id:"c079",type:"chunk",en:"I feel you.",ja:"気持ちわかるよ。"},
// 不同意・ためらい
{id:"c080",type:"chunk",en:"I don't think so.",ja:"そうは思わない。"},
{id:"c081",type:"chunk",en:"Not really.",ja:"そうでもないかな。"},
{id:"c082",type:"chunk",en:"I'm not so sure.",ja:"うーん、どうかな。"},
{id:"c083",type:"chunk",en:"I beg to differ.",ja:"私の意見は違うよ。"},
{id:"c084",type:"chunk",en:"I see your point, but...",ja:"言いたいことはわかるけど…"},
{id:"c085",type:"chunk",en:"I disagree.",ja:"反対だよ。"},
{id:"c086",type:"chunk",en:"Hmm, not exactly.",ja:"うーん、ちょっと違うかな。"},
{id:"c087",type:"chunk",en:"I have my doubts.",ja:"ちょっと疑わしいな。"},
{id:"c088",type:"chunk",en:"I wouldn't say that.",ja:"そうとは言えないかな。"},
{id:"c089",type:"chunk",en:"I'm not convinced.",ja:"納得いかないな。"},
{id:"c090",type:"chunk",en:"I don't buy it.",ja:"信じられないな。"},
{id:"c091",type:"chunk",en:"Are you sure?",ja:"本当に？"},
// 驚き
{id:"c092",type:"chunk",en:"No way!",ja:"ありえない！"},
{id:"c093",type:"chunk",en:"Are you serious?",ja:"本気で？"},
{id:"c094",type:"chunk",en:"You're kidding!",ja:"冗談でしょ！"},
{id:"c095",type:"chunk",en:"Are you kidding me?",ja:"冗談だよね？"},
{id:"c096",type:"chunk",en:"Get out of here!",ja:"うっそ！"},
{id:"c097",type:"chunk",en:"You're pulling my leg!",ja:"からかってるでしょ！"},
{id:"c098",type:"chunk",en:"I can't believe it!",ja:"信じられない！"},
{id:"c099",type:"chunk",en:"That's crazy!",ja:"すごい！信じられない！"},
{id:"c100",type:"chunk",en:"That's wild!",ja:"ぶっ飛んでる！"},
{id:"c101",type:"chunk",en:"That's nuts!",ja:"クレイジーだ！"},
{id:"c102",type:"chunk",en:"That's insane!",ja:"イカれてる！"},
{id:"c103",type:"chunk",en:"My mind is blown.",ja:"ぶっ飛んだわ。"},
{id:"c104",type:"chunk",en:"Wait, what?",ja:"えっ、なに？"},
{id:"c105",type:"chunk",en:"Seriously?",ja:"マジで？"},
{id:"c106",type:"chunk",en:"For real?",ja:"本当に？"},
{id:"c107",type:"chunk",en:"No kidding!",ja:"嘘でしょ！"},
{id:"c108",type:"chunk",en:"Whoa.",ja:"うわぁ。"},
{id:"c109",type:"chunk",en:"Oh my god.",ja:"なんてこと。"},
// ポジティブな反応
{id:"c110",type:"chunk",en:"That's awesome!",ja:"最高！"},
{id:"c111",type:"chunk",en:"That's amazing!",ja:"すごい！"},
{id:"c112",type:"chunk",en:"That's incredible!",ja:"信じられないくらいすごい！"},
{id:"c113",type:"chunk",en:"That's so cool!",ja:"超かっこいい！"},
{id:"c114",type:"chunk",en:"That's perfect.",ja:"完璧。"},
{id:"c115",type:"chunk",en:"Love it.",ja:"いいね。"},
{id:"c116",type:"chunk",en:"Sweet!",ja:"いいね！"},
{id:"c117",type:"chunk",en:"Nice one!",ja:"うまい！"},
{id:"c118",type:"chunk",en:"Right on!",ja:"その調子！"},
{id:"c119",type:"chunk",en:"Good for you!",ja:"よかったね！"},
{id:"c120",type:"chunk",en:"That's a relief.",ja:"ホッとした。"},
{id:"c121",type:"chunk",en:"That made my day.",ja:"おかげで最高の日になった。"},
{id:"c122",type:"chunk",en:"That's the best.",ja:"最高だね。"},
{id:"c123",type:"chunk",en:"I love that.",ja:"それ好き。"},
// ネガティブな反応
{id:"c124",type:"chunk",en:"That sucks.",ja:"最悪だね。"},
{id:"c125",type:"chunk",en:"That's terrible.",ja:"ひどいね。"},
{id:"c126",type:"chunk",en:"That's awful.",ja:"ひどい。"},
{id:"c127",type:"chunk",en:"That's a shame.",ja:"残念だね。"},
{id:"c128",type:"chunk",en:"That's too bad.",ja:"それは残念。"},
{id:"c129",type:"chunk",en:"That's rough.",ja:"それはつらいね。"},
{id:"c130",type:"chunk",en:"Bummer.",ja:"ガッカリ。"},
{id:"c131",type:"chunk",en:"What a pity.",ja:"なんて残念な。"},
{id:"c132",type:"chunk",en:"That's annoying.",ja:"イラっとするね。"},
{id:"c133",type:"chunk",en:"Oh no.",ja:"あちゃー。"},
{id:"c134",type:"chunk",en:"Yikes.",ja:"うわっ。"},
{id:"c135",type:"chunk",en:"Ouch.",ja:"いたっ。"},
{id:"c136",type:"chunk",en:"Not great.",ja:"よくないね。"},
// 好き嫌い
{id:"c137",type:"chunk",en:"I love it.",ja:"大好き。"},
{id:"c138",type:"chunk",en:"I really like it.",ja:"本当に好き。"},
{id:"c139",type:"chunk",en:"It's my favorite.",ja:"お気に入り。"},
{id:"c140",type:"chunk",en:"I'm a big fan.",ja:"大ファンだよ。"},
{id:"c141",type:"chunk",en:"I'm really into it.",ja:"めっちゃハマってる。"},
{id:"c142",type:"chunk",en:"I'm obsessed with it.",ja:"病みつきになってる。"},
{id:"c143",type:"chunk",en:"I can't get enough of it.",ja:"いくらあっても足りない。"},
{id:"c144",type:"chunk",en:"I'm not a fan.",ja:"あんまり好きじゃない。"},
{id:"c145",type:"chunk",en:"It's not for me.",ja:"私には合わない。"},
{id:"c146",type:"chunk",en:"Not my cup of tea.",ja:"私の好みじゃない。"},
{id:"c147",type:"chunk",en:"I'm not into it.",ja:"ハマってない。"},
{id:"c148",type:"chunk",en:"I can't stand it.",ja:"耐えられない。"},
{id:"c149",type:"chunk",en:"I hate it.",ja:"嫌い。"},
{id:"c150",type:"chunk",en:"Meh.",ja:"うーん、まあまあ。"},
// お礼
{id:"c151",type:"chunk",en:"Thank you so much.",ja:"本当にありがとう。"},
{id:"c152",type:"chunk",en:"Thanks a lot.",ja:"どうもありがとう。"},
{id:"c153",type:"chunk",en:"Thanks a million.",ja:"本当に本当にありがとう。"},
{id:"c154",type:"chunk",en:"Thanks a bunch.",ja:"ありがとね。"},
{id:"c155",type:"chunk",en:"Much appreciated.",ja:"感謝してる。"},
{id:"c156",type:"chunk",en:"I really appreciate it.",ja:"本当に感謝してる。"},
{id:"c157",type:"chunk",en:"I owe you one.",ja:"一つ借りができたね。"},
{id:"c158",type:"chunk",en:"You're a lifesaver.",ja:"命の恩人だよ。"},
{id:"c159",type:"chunk",en:"You're the best.",ja:"あなたって最高。"},
{id:"c160",type:"chunk",en:"That means a lot.",ja:"すごく嬉しい。"},
{id:"c161",type:"chunk",en:"Thanks for the help.",ja:"助けてくれてありがとう。"},
{id:"c162",type:"chunk",en:"Thanks for everything.",ja:"いろいろありがとう。"},
{id:"c163",type:"chunk",en:"I can't thank you enough.",ja:"感謝してもしきれない。"},
// どういたしまして
{id:"c164",type:"chunk",en:"You're welcome.",ja:"どういたしまして。"},
{id:"c165",type:"chunk",en:"No problem.",ja:"問題ないよ。"},
{id:"c166",type:"chunk",en:"No worries.",ja:"気にしないで。"},
{id:"c167",type:"chunk",en:"Anytime.",ja:"いつでもどうぞ。"},
{id:"c168",type:"chunk",en:"Don't mention it.",ja:"とんでもない。"},
{id:"c169",type:"chunk",en:"Glad to help.",ja:"力になれて嬉しい。"},
{id:"c170",type:"chunk",en:"Happy to help.",ja:"喜んで。"},
{id:"c171",type:"chunk",en:"My pleasure.",ja:"こちらこそ。"},
{id:"c172",type:"chunk",en:"Sure thing.",ja:"もちろん。"},
// 謝罪
{id:"c173",type:"chunk",en:"I'm sorry.",ja:"ごめんなさい。"},
{id:"c174",type:"chunk",en:"I'm so sorry.",ja:"本当にごめん。"},
{id:"c175",type:"chunk",en:"My bad.",ja:"ごめん、私のせい。"},
{id:"c176",type:"chunk",en:"My apologies.",ja:"申し訳ない。"},
{id:"c177",type:"chunk",en:"Sorry about that.",ja:"それについてごめん。"},
{id:"c178",type:"chunk",en:"Excuse me.",ja:"失礼します。"},
{id:"c179",type:"chunk",en:"Pardon me.",ja:"すみません。"},
{id:"c180",type:"chunk",en:"I didn't mean to.",ja:"そういうつもりじゃなかった。"},
{id:"c181",type:"chunk",en:"That's on me.",ja:"私のせいだ。"},
{id:"c182",type:"chunk",en:"It was my fault.",ja:"私が悪かった。"},
{id:"c183",type:"chunk",en:"Sorry to keep you waiting.",ja:"お待たせしてごめん。"},
{id:"c184",type:"chunk",en:"Sorry to bother you.",ja:"邪魔してごめん。"},
{id:"c185",type:"chunk",en:"Forgive me.",ja:"許してね。"},
// 大丈夫だよ
{id:"c186",type:"chunk",en:"It's okay.",ja:"大丈夫だよ。"},
{id:"c187",type:"chunk",en:"It's fine.",ja:"いいよ。"},
{id:"c188",type:"chunk",en:"Don't worry about it.",ja:"気にしないで。"},
{id:"c189",type:"chunk",en:"No big deal.",ja:"大したことじゃないよ。"},
{id:"c190",type:"chunk",en:"Forget it.",ja:"忘れていいよ。"},
{id:"c191",type:"chunk",en:"It happens.",ja:"よくあることだよ。"},
{id:"c192",type:"chunk",en:"No harm done.",ja:"なんともないよ。"},
{id:"c193",type:"chunk",en:"We're good.",ja:"問題ないよ。"},
{id:"c194",type:"chunk",en:"All good.",ja:"全部大丈夫。"},
// 意見・前置き
{id:"c195",type:"chunk",en:"I think so.",ja:"そう思うよ。"},
{id:"c196",type:"chunk",en:"I guess so.",ja:"たぶんそうかな。"},
{id:"c197",type:"chunk",en:"In my opinion,",ja:"私の意見では、"},
{id:"c198",type:"chunk",en:"If you ask me,",ja:"私に言わせれば、"},
{id:"c199",type:"chunk",en:"To be honest,",ja:"正直に言うと、"},
{id:"c200",type:"chunk",en:"Honestly,",ja:"正直、"},
{id:"c201",type:"chunk",en:"Frankly,",ja:"率直に言うと、"},
{id:"c202",type:"chunk",en:"To tell you the truth,",ja:"本当のことを言うと、"},
{id:"c203",type:"chunk",en:"Actually,",ja:"実は、"},
{id:"c204",type:"chunk",en:"The thing is,",ja:"問題はね、"},
{id:"c205",type:"chunk",en:"I mean,",ja:"つまり、"},
{id:"c206",type:"chunk",en:"You know what I mean?",ja:"わかるよね？"},
{id:"c207",type:"chunk",en:"I would say",ja:"私なら〜と言うね"},
{id:"c208",type:"chunk",en:"It seems like",ja:"〜のようだね"},
{id:"c209",type:"chunk",en:"It looks like",ja:"〜みたいだね"},
{id:"c210",type:"chunk",en:"Maybe.",ja:"たぶん。"},
{id:"c211",type:"chunk",en:"Probably.",ja:"おそらく。"},
{id:"c212",type:"chunk",en:"Perhaps.",ja:"たぶん。"},
{id:"c213",type:"chunk",en:"I'm not sure.",ja:"よくわからない。"},
{id:"c214",type:"chunk",en:"It depends.",ja:"場合によるね。"},
{id:"c215",type:"chunk",en:"It's hard to say.",ja:"なんとも言えないな。"},
{id:"c216",type:"chunk",en:"I have no idea.",ja:"全然わからない。"},
// つなぎ言葉
{id:"c217",type:"chunk",en:"You know,",ja:"ほら、"},
{id:"c218",type:"chunk",en:"Like,",ja:"なんか、"},
{id:"c219",type:"chunk",en:"So,",ja:"だから、"},
{id:"c220",type:"chunk",en:"Well,",ja:"えーと、"},
{id:"c221",type:"chunk",en:"Anyway,",ja:"とにかく、"},
{id:"c222",type:"chunk",en:"By the way,",ja:"ところで、"},
{id:"c223",type:"chunk",en:"Speaking of which,",ja:"そう言えば、"},
{id:"c224",type:"chunk",en:"That reminds me,",ja:"それで思い出した、"},
{id:"c225",type:"chunk",en:"On second thought,",ja:"よく考えてみたら、"},
{id:"c226",type:"chunk",en:"Come to think of it,",ja:"考えてみれば、"},
{id:"c227",type:"chunk",en:"As I was saying,",ja:"さっき言った通り、"},
{id:"c228",type:"chunk",en:"Long story short,",ja:"つまり手短に言うと、"},
{id:"c229",type:"chunk",en:"The point is,",ja:"要点は、"},
{id:"c230",type:"chunk",en:"Here's the thing,",ja:"実はね、"},
{id:"c231",type:"chunk",en:"Believe it or not,",ja:"信じるかどうかは別として、"},
{id:"c232",type:"chunk",en:"Truth be told,",ja:"本当のところ、"},
{id:"c233",type:"chunk",en:"Either way,",ja:"どちらにしても、"},
{id:"c234",type:"chunk",en:"In any case,",ja:"いずれにせよ、"},
// 食事
{id:"c235",type:"chunk",en:"Let's grab something to eat.",ja:"何か食べに行こう。"},
{id:"c236",type:"chunk",en:"Let's grab a bite.",ja:"軽く何か食べよう。"},
{id:"c237",type:"chunk",en:"Want to grab dinner?",ja:"夕飯どう？"},
{id:"c238",type:"chunk",en:"I could eat.",ja:"何か食べてもいいかな。"},
{id:"c239",type:"chunk",en:"I'm down for anything.",ja:"何でもいいよ。"},
{id:"c240",type:"chunk",en:"What sounds good?",ja:"何がいい？"},
{id:"c241",type:"chunk",en:"What are you in the mood for?",ja:"今何が食べたい気分？"},
{id:"c242",type:"chunk",en:"I'm craving pizza.",ja:"ピザが食べたい気分。"},
{id:"c243",type:"chunk",en:"I could go for some coffee.",ja:"コーヒーでも飲みたいな。"},
{id:"c244",type:"chunk",en:"I'll have the same.",ja:"同じものをください。"},
{id:"c245",type:"chunk",en:"Just water for me.",ja:"私はお水で。"},
{id:"c246",type:"chunk",en:"Can I get the check, please?",ja:"お会計お願いします。"},
{id:"c247",type:"chunk",en:"Could we split the bill?",ja:"割り勘でいい？"},
{id:"c248",type:"chunk",en:"It's on me.",ja:"私がおごるよ。"},
{id:"c249",type:"chunk",en:"Let me get this one.",ja:"今回は私が払うよ。"},
{id:"c250",type:"chunk",en:"Cheers!",ja:"乾杯！"},
{id:"c251",type:"chunk",en:"Dig in!",ja:"召し上がれ！"},
{id:"c252",type:"chunk",en:"Help yourself.",ja:"ご自由にどうぞ。"},
{id:"c253",type:"chunk",en:"This is delicious.",ja:"これおいしい。"},
{id:"c254",type:"chunk",en:"This hits the spot.",ja:"これたまらないね。"},
{id:"c255",type:"chunk",en:"I'm so full I can't move.",ja:"動けないくらい満腹。"},
{id:"c256",type:"chunk",en:"Save some for me.",ja:"私の分残しておいて。"},
// お願い
{id:"c257",type:"chunk",en:"Could you do me a favor?",ja:"お願いがあるんだけど。"},
{id:"c258",type:"chunk",en:"Can I ask you something?",ja:"聞いてもいい？"},
{id:"c259",type:"chunk",en:"Would you mind?",ja:"いいかな？"},
{id:"c260",type:"chunk",en:"Is it okay if I...?",ja:"〜してもいい？"},
{id:"c261",type:"chunk",en:"Do you have a minute?",ja:"ちょっと時間ある？"},
{id:"c262",type:"chunk",en:"Could you give me a hand?",ja:"手を貸してくれる？"},
{id:"c263",type:"chunk",en:"I need your help.",ja:"助けてほしい。"},
{id:"c264",type:"chunk",en:"Please?",ja:"お願い？"},
{id:"c265",type:"chunk",en:"If it's not too much trouble.",ja:"あまり手間でなければ。"},
{id:"c266",type:"chunk",en:"When you get a chance.",ja:"時間ができたときで。"},
{id:"c267",type:"chunk",en:"No rush.",ja:"急がなくていいよ。"},
{id:"c268",type:"chunk",en:"Whenever you have time.",ja:"いつでも空いてる時に。"},
{id:"c269",type:"chunk",en:"If you don't mind.",ja:"よかったら。"},
// 承諾・断り
{id:"c270",type:"chunk",en:"Sure.",ja:"いいよ。"},
{id:"c271",type:"chunk",en:"Sure, no problem.",ja:"もちろん大丈夫。"},
{id:"c272",type:"chunk",en:"Of course.",ja:"もちろん。"},
{id:"c273",type:"chunk",en:"Why not?",ja:"いいね、なんで？"},
{id:"c274",type:"chunk",en:"Absolutely, yes.",ja:"絶対そうしよう。"},
{id:"c275",type:"chunk",en:"Go ahead.",ja:"どうぞ。"},
{id:"c276",type:"chunk",en:"Feel free.",ja:"遠慮なくどうぞ。"},
{id:"c277",type:"chunk",en:"Be my guest.",ja:"どうぞご自由に。"},
{id:"c278",type:"chunk",en:"I'd love to.",ja:"喜んで。"},
{id:"c279",type:"chunk",en:"Sorry, I can't.",ja:"ごめん、無理。"},
{id:"c280",type:"chunk",en:"I wish I could.",ja:"できればいいんだけど。"},
{id:"c281",type:"chunk",en:"Maybe next time.",ja:"また今度ね。"},
{id:"c282",type:"chunk",en:"I'll pass.",ja:"今回はやめておく。"},
// 励まし
{id:"c283",type:"chunk",en:"You can do it!",ja:"できるよ！"},
{id:"c284",type:"chunk",en:"You've got this!",ja:"絶対できるよ！"},
{id:"c285",type:"chunk",en:"I believe in you.",ja:"君を信じてるよ。"},
{id:"c286",type:"chunk",en:"Don't give up.",ja:"あきらめないで。"},
{id:"c287",type:"chunk",en:"Keep going.",ja:"続けて。"},
{id:"c288",type:"chunk",en:"Hang in there.",ja:"頑張れ。"},
{id:"c289",type:"chunk",en:"Keep it up.",ja:"その調子。"},
{id:"c290",type:"chunk",en:"You're doing great.",ja:"よくやってるよ。"},
{id:"c291",type:"chunk",en:"That's the spirit.",ja:"その意気だ。"},
{id:"c292",type:"chunk",en:"Way to go!",ja:"やったね！"},
{id:"c293",type:"chunk",en:"Good for you.",ja:"よかったね。"},
{id:"c294",type:"chunk",en:"Nice work.",ja:"いい仕事だね。"},
{id:"c295",type:"chunk",en:"Well done.",ja:"よくできました。"},
{id:"c296",type:"chunk",en:"I'm proud of you.",ja:"誇りに思うよ。"},
{id:"c297",type:"chunk",en:"That's huge.",ja:"それすごいね。"},
{id:"c298",type:"chunk",en:"You crushed it!",ja:"圧勝したね！"},
{id:"c299",type:"chunk",en:"You nailed it!",ja:"完璧だった！"},
{id:"c300",type:"chunk",en:"That's the way!",ja:"その調子！"},
// 共感・慰め
{id:"c301",type:"chunk",en:"I'm sorry to hear that.",ja:"それは残念だね。"},
{id:"c302",type:"chunk",en:"That must be hard.",ja:"つらいよね。"},
{id:"c303",type:"chunk",en:"I'm here for you.",ja:"そばにいるよ。"},
{id:"c304",type:"chunk",en:"I've got your back.",ja:"味方だよ。"},
{id:"c305",type:"chunk",en:"Let me know if you need anything.",ja:"何かあったら言ってね。"},
{id:"c306",type:"chunk",en:"It'll be okay.",ja:"大丈夫になるよ。"},
{id:"c307",type:"chunk",en:"Everything will work out.",ja:"きっとうまくいくよ。"},
{id:"c308",type:"chunk",en:"This too shall pass.",ja:"これもいずれ過ぎ去るよ。"},
{id:"c309",type:"chunk",en:"Don't be too hard on yourself.",ja:"自分を責めすぎないで。"},
{id:"c310",type:"chunk",en:"Cut yourself some slack.",ja:"自分に少しは優しくして。"},
{id:"c311",type:"chunk",en:"I feel for you.",ja:"気持ちわかるよ。"},
{id:"c312",type:"chunk",en:"I know how you feel.",ja:"あなたの気持ちわかる。"},
{id:"c313",type:"chunk",en:"I can imagine.",ja:"想像できるよ。"},
// 日常の動き
{id:"c314",type:"chunk",en:"I'm home!",ja:"ただいま！"},
{id:"c315",type:"chunk",en:"Welcome back!",ja:"おかえり！"},
{id:"c316",type:"chunk",en:"I'm heading out.",ja:"出かけるよ。"},
{id:"c317",type:"chunk",en:"I'm on my way.",ja:"今向かってる。"},
{id:"c318",type:"chunk",en:"I'm running late.",ja:"遅れそう。"},
{id:"c319",type:"chunk",en:"I'll be there in five.",ja:"5分で行くよ。"},
{id:"c320",type:"chunk",en:"I'm almost there.",ja:"もうすぐ着くよ。"},
{id:"c321",type:"chunk",en:"Be right back.",ja:"すぐ戻る。"},
{id:"c322",type:"chunk",en:"Hold on a sec.",ja:"ちょっと待って。"},
{id:"c323",type:"chunk",en:"Give me a minute.",ja:"少しちょうだい。"},
{id:"c324",type:"chunk",en:"I'm coming.",ja:"今行く。"},
{id:"c325",type:"chunk",en:"One sec.",ja:"ちょっとだけ。"},
{id:"c326",type:"chunk",en:"Hang on.",ja:"待って。"},
// 気軽な質問
{id:"c327",type:"chunk",en:"What's going on?",ja:"どうしたの？"},
{id:"c328",type:"chunk",en:"What's new?",ja:"何か新しいことある？"},
{id:"c329",type:"chunk",en:"Anything new?",ja:"何か変わった？"},
{id:"c330",type:"chunk",en:"What have you been up to?",ja:"最近何してた？"},
{id:"c331",type:"chunk",en:"How's life?",ja:"人生どう？"},
{id:"c332",type:"chunk",en:"How's everything?",ja:"全部どう？"},
{id:"c333",type:"chunk",en:"How's work?",ja:"仕事はどう？"},
{id:"c334",type:"chunk",en:"How's the family?",ja:"ご家族は元気？"},
{id:"c335",type:"chunk",en:"What's the plan?",ja:"予定どうする？"},
{id:"c336",type:"chunk",en:"What are you up to?",ja:"何してるの？"},
{id:"c337",type:"chunk",en:"What's on your mind?",ja:"何を考えてるの？"},
{id:"c338",type:"chunk",en:"Where have you been?",ja:"今までどこにいたの？"},
{id:"c339",type:"chunk",en:"Where are you headed?",ja:"どこに向かってるの？"},
{id:"c340",type:"chunk",en:"What brings you here?",ja:"どうしてここに？"},
{id:"c341",type:"chunk",en:"What's the occasion?",ja:"何かあったの？"},
{id:"c342",type:"chunk",en:"What's wrong?",ja:"どうしたの？"},
{id:"c343",type:"chunk",en:"What happened?",ja:"何があったの？"},
{id:"c344",type:"chunk",en:"Anything else?",ja:"他には？"},
// 電話・SNS
{id:"c345",type:"chunk",en:"Give me a call.",ja:"電話してね。"},
{id:"c346",type:"chunk",en:"I'll call you back.",ja:"折り返すよ。"},
{id:"c347",type:"chunk",en:"Text me.",ja:"メッセージしてね。"},
{id:"c348",type:"chunk",en:"Shoot me a message.",ja:"連絡してね。"},
{id:"c349",type:"chunk",en:"DM me.",ja:"DMしてね。"},
{id:"c350",type:"chunk",en:"Let me check my phone.",ja:"ちょっとスマホ見させて。"},
{id:"c351",type:"chunk",en:"My phone is dying.",ja:"バッテリーが切れそう。"},
{id:"c352",type:"chunk",en:"I'll send you the link.",ja:"リンク送るよ。"},
{id:"c353",type:"chunk",en:"Did you see my message?",ja:"私のメッセージ見た？"},
{id:"c354",type:"chunk",en:"Sorry, I missed your call.",ja:"電話気づかなかった、ごめん。"},
{id:"c355",type:"chunk",en:"Can you hear me?",ja:"聞こえる？"},
{id:"c356",type:"chunk",en:"You're breaking up.",ja:"声が途切れてるよ。"},
{id:"c357",type:"chunk",en:"Let me put you on speaker.",ja:"スピーカーにするね。"},
{id:"c358",type:"chunk",en:"I'll call you right back.",ja:"すぐかけ直す。"},
// 体調
{id:"c359",type:"chunk",en:"I don't feel well.",ja:"具合悪い。"},
{id:"c360",type:"chunk",en:"I'm coming down with something.",ja:"風邪ひきそう。"},
{id:"c361",type:"chunk",en:"I think I'm getting sick.",ja:"体調崩しそう。"},
{id:"c362",type:"chunk",en:"I have a headache.",ja:"頭が痛い。"},
{id:"c363",type:"chunk",en:"My back hurts.",ja:"腰が痛い。"},
{id:"c364",type:"chunk",en:"My head is killing me.",ja:"頭が割れそうに痛い。"},
{id:"c365",type:"chunk",en:"I'm feeling under the weather.",ja:"なんか調子悪い。"},
{id:"c366",type:"chunk",en:"I feel awful.",ja:"気分が最悪。"},
{id:"c367",type:"chunk",en:"Are you okay?",ja:"大丈夫？"},
{id:"c368",type:"chunk",en:"You look pale.",ja:"顔色悪いよ。"},
{id:"c369",type:"chunk",en:"You don't look so good.",ja:"あんまり元気そうじゃないね。"},
{id:"c370",type:"chunk",en:"Get well soon.",ja:"早く良くなってね。"},
{id:"c371",type:"chunk",en:"Feel better.",ja:"お大事に。"},
{id:"c372",type:"chunk",en:"Take care of yourself.",ja:"体に気をつけてね。"},
{id:"c373",type:"chunk",en:"Get some rest.",ja:"ゆっくり休んでね。"},
{id:"c374",type:"chunk",en:"Drink lots of water.",ja:"水いっぱい飲んでね。"},
{id:"c375",type:"chunk",en:"I'm feeling better.",ja:"良くなってきた。"},
// 時間・予定
{id:"c376",type:"chunk",en:"What time is it?",ja:"今何時？"},
{id:"c377",type:"chunk",en:"Do you have the time?",ja:"時間わかる？"},
{id:"c378",type:"chunk",en:"I'm running late.",ja:"遅れそう。"},
{id:"c379",type:"chunk",en:"I'll be late.",ja:"遅れるよ。"},
{id:"c380",type:"chunk",en:"I'll be there soon.",ja:"すぐ着くよ。"},
{id:"c381",type:"chunk",en:"Let's meet up.",ja:"会おう。"},
{id:"c382",type:"chunk",en:"Are you free tonight?",ja:"今夜暇？"},
{id:"c383",type:"chunk",en:"Are you busy?",ja:"忙しい？"},
{id:"c384",type:"chunk",en:"I have plans.",ja:"用事があるんだ。"},
{id:"c385",type:"chunk",en:"I'm tied up.",ja:"手が離せない。"},
{id:"c386",type:"chunk",en:"I'm swamped.",ja:"忙しすぎる。"},
{id:"c387",type:"chunk",en:"I'll get back to you.",ja:"あとで連絡するね。"},
{id:"c388",type:"chunk",en:"Let me check my schedule.",ja:"スケジュール確認するね。"},
{id:"c389",type:"chunk",en:"Can we reschedule?",ja:"日程変更できる？"},
{id:"c390",type:"chunk",en:"Can we push it back?",ja:"後ろにずらせる？"},
{id:"c391",type:"chunk",en:"Can we move it up?",ja:"前倒しできる？"},
{id:"c392",type:"chunk",en:"Sometime next week.",ja:"来週のどこかで。"},
{id:"c393",type:"chunk",en:"Sooner rather than later.",ja:"早めにね。"},
{id:"c394",type:"chunk",en:"right now",ja:"今すぐ"},
{id:"c395",type:"chunk",en:"right away",ja:"ただちに"},
{id:"c396",type:"chunk",en:"in a bit",ja:"もう少ししたら"},
{id:"c397",type:"chunk",en:"later on",ja:"あとで"},
// 聞き返し
{id:"c398",type:"chunk",en:"What did you say?",ja:"なんて言ったの？"},
{id:"c399",type:"chunk",en:"Could you repeat that?",ja:"もう一度言ってくれる？"},
{id:"c400",type:"chunk",en:"Say that again?",ja:"もう一回言って？"},
{id:"c401",type:"chunk",en:"I didn't catch that.",ja:"聞き取れなかった。"},
{id:"c402",type:"chunk",en:"Sorry, what?",ja:"ごめん、なに？"},
{id:"c403",type:"chunk",en:"Come again?",ja:"もう一度？"},
{id:"c404",type:"chunk",en:"What do you mean?",ja:"どういう意味？"},
{id:"c405",type:"chunk",en:"I'm not following.",ja:"話についていけてない。"},
{id:"c406",type:"chunk",en:"I don't get it.",ja:"理解できないな。"},
{id:"c407",type:"chunk",en:"Got it.",ja:"わかった。"},
{id:"c408",type:"chunk",en:"I see.",ja:"なるほど。"},
{id:"c409",type:"chunk",en:"Makes sense.",ja:"納得。"},
{id:"c410",type:"chunk",en:"Now I understand.",ja:"やっとわかった。"},
// 提案
{id:"c411",type:"chunk",en:"How about we go out?",ja:"出かけない？"},
{id:"c412",type:"chunk",en:"Why don't we try it?",ja:"やってみない？"},
{id:"c413",type:"chunk",en:"Why not give it a try?",ja:"試してみたら？"},
{id:"c414",type:"chunk",en:"What do you say we leave?",ja:"そろそろ出ない？"},
{id:"c415",type:"chunk",en:"Let's give it a shot.",ja:"やってみよう。"},
{id:"c416",type:"chunk",en:"Let's give it a try.",ja:"試してみよう。"},
{id:"c417",type:"chunk",en:"Let's see how it goes.",ja:"様子を見よう。"},
{id:"c418",type:"chunk",en:"Worth a shot.",ja:"やってみる価値はある。"},
{id:"c419",type:"chunk",en:"It can't hurt.",ja:"損はないよ。"},
{id:"c420",type:"chunk",en:"Maybe we should leave.",ja:"そろそろ出た方がいいかも。"},
{id:"c421",type:"chunk",en:"We could always try later.",ja:"あとで試すこともできるよ。"},
{id:"c422",type:"chunk",en:"Just a thought.",ja:"ちょっとした提案だけど。"},
{id:"c423",type:"chunk",en:"Take it or leave it.",ja:"嫌なら断っていいよ。"},
// 決定
{id:"c424",type:"chunk",en:"It's up to you.",ja:"あなた次第。"},
{id:"c425",type:"chunk",en:"You decide.",ja:"決めて。"},
{id:"c426",type:"chunk",en:"Your call.",ja:"任せるよ。"},
{id:"c427",type:"chunk",en:"Whatever you want.",ja:"何でもいいよ。"},
{id:"c428",type:"chunk",en:"I don't mind.",ja:"気にしないよ。"},
{id:"c429",type:"chunk",en:"Either is fine.",ja:"どちらでもいい。"},
{id:"c430",type:"chunk",en:"I'm easy.",ja:"こだわりないよ。"},
{id:"c431",type:"chunk",en:"I'm flexible.",ja:"なんでも合わせるよ。"},
{id:"c432",type:"chunk",en:"I can't decide.",ja:"決められない。"},
{id:"c433",type:"chunk",en:"I'm torn.",ja:"迷ってる。"},
{id:"c434",type:"chunk",en:"I'll think about it.",ja:"考えておく。"},
{id:"c435",type:"chunk",en:"Let me sleep on it.",ja:"一晩考えさせて。"},
{id:"c436",type:"chunk",en:"I'm leaning toward yes.",ja:"イエスの方に傾いてる。"},
// 締め
{id:"c437",type:"chunk",en:"That's it.",ja:"以上。"},
{id:"c438",type:"chunk",en:"That's all.",ja:"それだけ。"},
{id:"c439",type:"chunk",en:"That's about it.",ja:"だいたいそれくらい。"},
{id:"c440",type:"chunk",en:"That sums it up.",ja:"まとめるとそんな感じ。"},
{id:"c441",type:"chunk",en:"That's a wrap.",ja:"これで終わり。"},
{id:"c442",type:"chunk",en:"Long story short, it failed.",ja:"早い話、失敗した。"},
{id:"c443",type:"chunk",en:"In short,",ja:"要するに、"},
{id:"c444",type:"chunk",en:"Bottom line,",ja:"結論を言うと、"},
{id:"c445",type:"chunk",en:"All in all,",ja:"全体として、"},
{id:"c446",type:"chunk",en:"At the end of the day,",ja:"結局のところ、"},
{id:"c447",type:"chunk",en:"One way or another,",ja:"なんとかして、"},
{id:"c448",type:"chunk",en:"So yeah.",ja:"そういうこと。"},
{id:"c449",type:"chunk",en:"And that's that.",ja:"それでおしまい。"},
// 慣用表現・イディオム
{id:"c450",type:"chunk",en:"It's a piece of cake.",ja:"楽勝だよ。"},
{id:"c451",type:"chunk",en:"It's not rocket science.",ja:"そんなに難しくないよ。"},
{id:"c452",type:"chunk",en:"I'm all ears.",ja:"聞いてるよ。"},
{id:"c453",type:"chunk",en:"Cut to the chase.",ja:"本題に入ろう。"},
{id:"c454",type:"chunk",en:"Let's hit the road.",ja:"そろそろ出発しよう。"},
{id:"c455",type:"chunk",en:"I'm gonna hit the sack.",ja:"もう寝るよ。"},
{id:"c456",type:"chunk",en:"Let's call it a day.",ja:"今日はもうこれで終わりにしよう。"},
{id:"c457",type:"chunk",en:"Let's call it a night.",ja:"今夜はもうお開きにしよう。"},
{id:"c458",type:"chunk",en:"Sleep on it.",ja:"一晩考えてみて。"},
{id:"c459",type:"chunk",en:"Bite the bullet.",ja:"覚悟を決めてやれ。"},
{id:"c460",type:"chunk",en:"Break a leg!",ja:"頑張って！"},
{id:"c461",type:"chunk",en:"Cross your fingers.",ja:"幸運を祈ろう。"},
{id:"c462",type:"chunk",en:"Fingers crossed.",ja:"うまくいきますように。"},
{id:"c463",type:"chunk",en:"Knock on wood.",ja:"縁起担ぎ。"},
{id:"c464",type:"chunk",en:"It rings a bell.",ja:"聞き覚えがある。"},
{id:"c465",type:"chunk",en:"Out of the blue.",ja:"突然のことだった。"},
{id:"c466",type:"chunk",en:"Once in a blue moon.",ja:"ごくまれに。"},
{id:"c467",type:"chunk",en:"The ball is in your court.",ja:"あなた次第だよ。"},
{id:"c468",type:"chunk",en:"Let's play it by ear.",ja:"成り行きでいこう。"},
{id:"c469",type:"chunk",en:"Better safe than sorry.",ja:"用心するに越したことはない。"},
{id:"c470",type:"chunk",en:"It's a small world.",ja:"世間は狭いね。"},
{id:"c471",type:"chunk",en:"That's life.",ja:"それが人生さ。"},
{id:"c472",type:"chunk",en:"Easy come, easy go.",ja:"得やすいものは失いやすい。"},
{id:"c473",type:"chunk",en:"Time flies.",ja:"時が経つのは早い。"},
{id:"c474",type:"chunk",en:"Time will tell.",ja:"時間が経てばわかるよ。"},
{id:"c475",type:"chunk",en:"No pain, no gain.",ja:"苦労なしの成功はない。"},
{id:"c476",type:"chunk",en:"The early bird gets the worm.",ja:"早起きは三文の徳。"},
{id:"c477",type:"chunk",en:"When in Rome.",ja:"郷に入っては郷に従え。"},
{id:"c478",type:"chunk",en:"It takes two to tango.",ja:"二人ともに責任がある。"},
{id:"c479",type:"chunk",en:"That's the last straw.",ja:"もう我慢の限界だ。"},
{id:"c480",type:"chunk",en:"Speak of the devil.",ja:"噂をすれば影。"},
{id:"c481",type:"chunk",en:"A blessing in disguise.",ja:"不幸中の幸い。"},
{id:"c482",type:"chunk",en:"You hit the nail on the head.",ja:"まさに核心を突いたね。"},
{id:"c483",type:"chunk",en:"It got out of hand.",ja:"手に負えなくなった。"},
{id:"c484",type:"chunk",en:"Off the top of my head,",ja:"パッと思いつくのは、"},
{id:"c485",type:"chunk",en:"It's on the tip of my tongue.",ja:"喉まで出かかってる。"},
{id:"c486",type:"chunk",en:"Easier said than done.",ja:"言うは易し行うは難し。"},
{id:"c487",type:"chunk",en:"Practice makes perfect.",ja:"練習あるのみ。"},
{id:"c488",type:"chunk",en:"Look on the bright side.",ja:"前向きに考えよう。"},
{id:"c489",type:"chunk",en:"The grass is always greener.",ja:"隣の芝生は青い。"},
// 句動詞
{id:"c490",type:"chunk",en:"Let's hang out.",ja:"一緒に過ごそう。"},
{id:"c491",type:"chunk",en:"Hang on a second.",ja:"ちょっと待って。"},
{id:"c492",type:"chunk",en:"Don't hang up on me.",ja:"電話切らないで。"},
{id:"c493",type:"chunk",en:"I'll pick you up.",ja:"迎えに行くよ。"},
{id:"c494",type:"chunk",en:"Pick out something nice.",ja:"何か良いの選んで。"},
{id:"c495",type:"chunk",en:"I'll drop it off.",ja:"届けに行くよ。"},
{id:"c496",type:"chunk",en:"Drop by anytime.",ja:"いつでも寄ってね。"},
{id:"c497",type:"chunk",en:"He didn't show up.",ja:"彼来なかったよ。"},
{id:"c498",type:"chunk",en:"Turn it up.",ja:"音量上げて。"},
{id:"c499",type:"chunk",en:"Turn it down.",ja:"音量下げて。"},
{id:"c500",type:"chunk",en:"Turn it off.",ja:"消して。"},
{id:"c501",type:"chunk",en:"Turn it on.",ja:"つけて。"},
{id:"c502",type:"chunk",en:"Let me look it up.",ja:"調べてみるね。"},
{id:"c503",type:"chunk",en:"Look out!",ja:"危ない！"},
{id:"c504",type:"chunk",en:"I'll look into it.",ja:"調べてみる。"},
{id:"c505",type:"chunk",en:"I'm looking forward to it.",ja:"楽しみにしてる。"},
{id:"c506",type:"chunk",en:"Time to get up.",ja:"起きる時間だよ。"},
{id:"c507",type:"chunk",en:"Get off my back.",ja:"うるさく言わないで。"},
{id:"c508",type:"chunk",en:"Let's get on with it.",ja:"さっさと始めよう。"},
{id:"c509",type:"chunk",en:"Do you two get along?",ja:"二人は仲良くやってる？"},
{id:"c510",type:"chunk",en:"Get over it.",ja:"立ち直って。"},
{id:"c511",type:"chunk",en:"Get back to me on that.",ja:"それについて返事ちょうだい。"},
{id:"c512",type:"chunk",en:"Let's get going.",ja:"そろそろ行こう。"},
{id:"c513",type:"chunk",en:"I want to get rid of it.",ja:"これ処分したい。"},
{id:"c514",type:"chunk",en:"We're running out of time.",ja:"時間がなくなってきた。"},
{id:"c515",type:"chunk",en:"I ran into her yesterday.",ja:"昨日彼女に偶然会った。"},
{id:"c516",type:"chunk",en:"Cut it out!",ja:"やめて！"},
{id:"c517",type:"chunk",en:"Knock it off!",ja:"いい加減にして！"},
{id:"c518",type:"chunk",en:"Calm down.",ja:"落ち着いて。"},
{id:"c519",type:"chunk",en:"Settle down.",ja:"静かにして。"},
{id:"c520",type:"chunk",en:"Slow down.",ja:"ゆっくり。"},
{id:"c521",type:"chunk",en:"Speed it up.",ja:"急いで。"},
{id:"c522",type:"chunk",en:"Let's catch up soon.",ja:"近いうちに会って話そう。"},
{id:"c523",type:"chunk",en:"Come on!",ja:"早く！"},
{id:"c524",type:"chunk",en:"Come over to my place.",ja:"家に来てよ。"},
{id:"c525",type:"chunk",en:"I came up with an idea.",ja:"アイデアを思いついた。"},
{id:"c526",type:"chunk",en:"Don't bring it up.",ja:"その話は出さないで。"},
{id:"c527",type:"chunk",en:"Have a seat.",ja:"座って。"},
{id:"c528",type:"chunk",en:"Stand by for a minute.",ja:"少し待機して。"},
{id:"c529",type:"chunk",en:"I have to take off.",ja:"もう出ないと。"},
{id:"c530",type:"chunk",en:"Can you take over?",ja:"代わってくれる？"},
{id:"c531",type:"chunk",en:"I almost passed out.",ja:"気絶しそうだった。"},
{id:"c532",type:"chunk",en:"Wake up!",ja:"起きて！"},
{id:"c533",type:"chunk",en:"Don't show off.",ja:"自慢しないで。"},
{id:"c534",type:"chunk",en:"I'll find out.",ja:"調べておくよ。"},
// 仕事・職場
{id:"c535",type:"chunk",en:"I'm slammed.",ja:"超忙しい。"},
{id:"c536",type:"chunk",en:"Let's hop on a call.",ja:"電話会議しよう。"},
{id:"c537",type:"chunk",en:"Let's circle back.",ja:"あとで戻って話そう。"},
{id:"c538",type:"chunk",en:"I'll loop you in.",ja:"君も巻き込むね。"},
{id:"c539",type:"chunk",en:"Let's touch base later.",ja:"あとで連絡取り合おう。"},
{id:"c540",type:"chunk",en:"Ping me.",ja:"連絡してね。"},
{id:"c541",type:"chunk",en:"Let me know.",ja:"教えてね。"},
{id:"c542",type:"chunk",en:"I'll keep you posted.",ja:"進捗報告するね。"},
{id:"c543",type:"chunk",en:"Forward it to me.",ja:"私に転送して。"},
{id:"c544",type:"chunk",en:"I'll get on it.",ja:"すぐ取り掛かるよ。"},
{id:"c545",type:"chunk",en:"I'm on it.",ja:"対応してるよ。"},
{id:"c546",type:"chunk",en:"Consider it done.",ja:"任せて。"},
{id:"c547",type:"chunk",en:"Leave it to me.",ja:"私に任せて。"},
{id:"c548",type:"chunk",en:"Quick question.",ja:"ちょっと質問。"},
{id:"c549",type:"chunk",en:"Just a heads up,",ja:"ちょっと先に伝えておくね、"},
{id:"c550",type:"chunk",en:"For the record,",ja:"念のため言っておくと、"},
{id:"c551",type:"chunk",en:"Off the record,",ja:"ここだけの話だけど、"},
{id:"c552",type:"chunk",en:"Let's table this.",ja:"これは保留にしよう。"},
{id:"c553",type:"chunk",en:"We'll figure it out.",ja:"なんとかなるよ。"},
{id:"c554",type:"chunk",en:"It's a work in progress.",ja:"まだ作業中。"},
{id:"c555",type:"chunk",en:"I'll take a look.",ja:"見ておくよ。"},
{id:"c556",type:"chunk",en:"Sounds like a plan.",ja:"いいね、そうしよう。"},
// お金・買い物
{id:"c557",type:"chunk",en:"It's on sale.",ja:"セール中だよ。"},
{id:"c558",type:"chunk",en:"What a deal!",ja:"すごい掘り出し物！"},
{id:"c559",type:"chunk",en:"That's a steal.",ja:"超お得。"},
{id:"c560",type:"chunk",en:"That's a rip-off.",ja:"ぼったくりだ。"},
{id:"c561",type:"chunk",en:"It's pricey.",ja:"値段高めだね。"},
{id:"c562",type:"chunk",en:"It's expensive.",ja:"高い。"},
{id:"c563",type:"chunk",en:"It's a bargain.",ja:"お買い得。"},
{id:"c564",type:"chunk",en:"I can't afford it.",ja:"そんな余裕ない。"},
{id:"c565",type:"chunk",en:"It's worth it.",ja:"その価値はある。"},
{id:"c566",type:"chunk",en:"It's not worth it.",ja:"価値ないよ。"},
{id:"c567",type:"chunk",en:"Cash or card?",ja:"現金、それともカード？"},
{id:"c568",type:"chunk",en:"Do you take cards?",ja:"カード使えますか？"},
{id:"c569",type:"chunk",en:"Keep the change.",ja:"お釣りはとっといて。"},
{id:"c570",type:"chunk",en:"I'm short on cash.",ja:"現金が足りない。"},
{id:"c571",type:"chunk",en:"I'm broke.",ja:"金欠だ。"},
{id:"c572",type:"chunk",en:"I'm saving up.",ja:"貯金してるところ。"},
{id:"c573",type:"chunk",en:"Treat yourself.",ja:"自分にご褒美を。"},
{id:"c574",type:"chunk",en:"Let's split the bill.",ja:"割り勘にしよう。"},
// 移動・道案内
{id:"c575",type:"chunk",en:"I'm lost.",ja:"道に迷った。"},
{id:"c576",type:"chunk",en:"How do I get to the station?",ja:"駅へはどう行きますか？"},
{id:"c577",type:"chunk",en:"It's just around the corner.",ja:"すぐそこの角だよ。"},
{id:"c578",type:"chunk",en:"It's down the street.",ja:"この通りを行ったところ。"},
{id:"c579",type:"chunk",en:"It's two blocks away.",ja:"二ブロック先。"},
{id:"c580",type:"chunk",en:"Go straight.",ja:"まっすぐ行って。"},
{id:"c581",type:"chunk",en:"Make a left.",ja:"左に曲がって。"},
{id:"c582",type:"chunk",en:"Make a right.",ja:"右に曲がって。"},
{id:"c583",type:"chunk",en:"You can't miss it.",ja:"絶対見つかるよ。"},
{id:"c584",type:"chunk",en:"It's right there.",ja:"すぐそこだよ。"},
{id:"c585",type:"chunk",en:"We're almost there.",ja:"もうすぐだよ。"},
{id:"c586",type:"chunk",en:"Are we there yet?",ja:"もう着く？"},
{id:"c587",type:"chunk",en:"I'll show you the way.",ja:"道案内するよ。"},
// 天気の雑談
{id:"c588",type:"chunk",en:"It's freezing.",ja:"凍えるほど寒い。"},
{id:"c589",type:"chunk",en:"It's boiling.",ja:"うだるように暑い。"},
{id:"c590",type:"chunk",en:"It's pouring.",ja:"土砂降りだ。"},
{id:"c591",type:"chunk",en:"It's nice out.",ja:"外気持ちいいね。"},
{id:"c592",type:"chunk",en:"What a beautiful day.",ja:"なんて素敵な日。"},
{id:"c593",type:"chunk",en:"It's gonna rain.",ja:"雨が降りそう。"},
{id:"c594",type:"chunk",en:"It looks like rain.",ja:"雨っぽいね。"},
{id:"c595",type:"chunk",en:"It's so muggy.",ja:"蒸し暑いね。"},
{id:"c596",type:"chunk",en:"It's a heat wave.",ja:"猛暑だ。"},
{id:"c597",type:"chunk",en:"The weather is gorgeous.",ja:"天気最高だね。"},
// 恋愛・人間関係
{id:"c598",type:"chunk",en:"I have a crush on him.",ja:"彼に片思いしてる。"},
{id:"c599",type:"chunk",en:"I have a crush on her.",ja:"彼女に片思いしてる。"},
{id:"c600",type:"chunk",en:"We're just friends.",ja:"ただの友達だよ。"},
{id:"c601",type:"chunk",en:"We hit it off.",ja:"意気投合したよ。"},
{id:"c602",type:"chunk",en:"We clicked.",ja:"フィーリングが合った。"},
{id:"c603",type:"chunk",en:"We're seeing each other.",ja:"付き合ってる。"},
{id:"c604",type:"chunk",en:"I miss you.",ja:"会いたい。"},
{id:"c605",type:"chunk",en:"I miss you so much.",ja:"すごく会いたい。"},
{id:"c606",type:"chunk",en:"I'm thinking of you.",ja:"あなたのこと考えてる。"},
{id:"c607",type:"chunk",en:"I love you.",ja:"愛してる。"},
{id:"c608",type:"chunk",en:"I love you too.",ja:"私も愛してる。"},
{id:"c609",type:"chunk",en:"I'm into you.",ja:"あなたに夢中。"},
{id:"c610",type:"chunk",en:"We broke up.",ja:"別れた。"},
// 家庭
{id:"c611",type:"chunk",en:"Dinner's ready!",ja:"ごはんできたよ！"},
{id:"c612",type:"chunk",en:"Time to eat!",ja:"食べる時間だよ！"},
{id:"c613",type:"chunk",en:"Wash your hands.",ja:"手を洗って。"},
{id:"c614",type:"chunk",en:"Help me set the table.",ja:"テーブルセッティング手伝って。"},
{id:"c615",type:"chunk",en:"I'll do the dishes.",ja:"皿洗いするよ。"},
{id:"c616",type:"chunk",en:"Take out the trash.",ja:"ゴミ出して。"},
{id:"c617",type:"chunk",en:"Did you lock the door?",ja:"鍵かけた？"},
{id:"c618",type:"chunk",en:"Turn off the lights.",ja:"電気消して。"},
{id:"c619",type:"chunk",en:"Shut the door.",ja:"ドア閉めて。"},
{id:"c620",type:"chunk",en:"Keep it down.",ja:"静かにして。"},
{id:"c621",type:"chunk",en:"Be quiet.",ja:"静かに。"},
{id:"c622",type:"chunk",en:"Be nice.",ja:"優しくしてね。"},
{id:"c623",type:"chunk",en:"Behave yourself.",ja:"行儀よくして。"},
// 愚痴・不満
{id:"c624",type:"chunk",en:"This is so annoying.",ja:"これマジでイラつく。"},
{id:"c625",type:"chunk",en:"This is ridiculous.",ja:"バカげてる。"},
{id:"c626",type:"chunk",en:"Give me a break.",ja:"勘弁してよ。"},
{id:"c627",type:"chunk",en:"This is the worst.",ja:"最悪。"},
{id:"c628",type:"chunk",en:"I can't even.",ja:"もう無理。"},
{id:"c629",type:"chunk",en:"I've had enough.",ja:"もうたくさん。"},
{id:"c630",type:"chunk",en:"I'm done with this.",ja:"もうこれは終わりにする。"},
{id:"c631",type:"chunk",en:"That's not fair.",ja:"それは不公平だよ。"},
{id:"c632",type:"chunk",en:"This is killing me.",ja:"これマジでつらい。"},
{id:"c633",type:"chunk",en:"What a pain.",ja:"面倒くさい。"},
{id:"c634",type:"chunk",en:"What a mess.",ja:"なんてぐちゃぐちゃ。"},
{id:"c635",type:"chunk",en:"Just my luck.",ja:"私らしいよ（運悪く）。"},
{id:"c636",type:"chunk",en:"I've had it up to here.",ja:"もう限界。"},
// 励まし・安心
{id:"c637",type:"chunk",en:"You're not alone.",ja:"あなただけじゃないよ。"},
{id:"c638",type:"chunk",en:"I'm here for you.",ja:"そばにいるよ。"},
{id:"c639",type:"chunk",en:"Don't worry.",ja:"心配しないで。"},
{id:"c640",type:"chunk",en:"Don't sweat it.",ja:"気にしないで。"},
{id:"c641",type:"chunk",en:"It's not your fault.",ja:"あなたのせいじゃない。"},
{id:"c642",type:"chunk",en:"It's not the end of the world.",ja:"世界の終わりじゃないよ。"},
{id:"c643",type:"chunk",en:"We'll figure it out.",ja:"なんとかなるよ。"},
{id:"c644",type:"chunk",en:"We've got this.",ja:"私たちならできる。"},
{id:"c645",type:"chunk",en:"It's going to be fine.",ja:"きっと大丈夫。"},
{id:"c646",type:"chunk",en:"You did your best.",ja:"最善を尽くしたよ。"},
{id:"c647",type:"chunk",en:"That's what matters.",ja:"それが大事なんだ。"},
{id:"c648",type:"chunk",en:"It's the thought that counts.",ja:"気持ちが大事。"},
{id:"c649",type:"chunk",en:"Tomorrow's a new day.",ja:"明日は新しい日だよ。"},
// 別れ際のひとこと
{id:"c650",type:"chunk",en:"I gotta go.",ja:"もう行かなきゃ。"},
{id:"c651",type:"chunk",en:"I'll let you go.",ja:"もう切るね。"},
{id:"c652",type:"chunk",en:"I'd better get going.",ja:"そろそろ行かないと。"},
{id:"c653",type:"chunk",en:"I'll catch you later.",ja:"また後でね。"},
{id:"c654",type:"chunk",en:"Stay safe.",ja:"気をつけてね。"},
{id:"c655",type:"chunk",en:"Stay warm.",ja:"暖かくしてね。"},
{id:"c656",type:"chunk",en:"Sweet dreams.",ja:"いい夢を。"},
{id:"c657",type:"chunk",en:"Sleep tight.",ja:"ぐっすり眠ってね。"},
{id:"c658",type:"chunk",en:"Talk soon.",ja:"また近いうちに話そう。"},
{id:"c659",type:"chunk",en:"Good night, sleep well.",ja:"おやすみ、よく眠ってね。"},
// その他ネイティブ表現
{id:"c660",type:"chunk",en:"Whatever.",ja:"どうでもいい。"},
{id:"c661",type:"chunk",en:"Whatever you say.",ja:"あなたの好きにして。"},
{id:"c662",type:"chunk",en:"Suit yourself.",ja:"勝手にして。"},
{id:"c663",type:"chunk",en:"It is what it is.",ja:"仕方ないさ。"},
{id:"c664",type:"chunk",en:"Story of my life.",ja:"いつものことだよ。"},
{id:"c665",type:"chunk",en:"Oh well.",ja:"まあいいか。"},
{id:"c666",type:"chunk",en:"Easy peasy.",ja:"超簡単。"},
{id:"c667",type:"chunk",en:"Easy does it.",ja:"そっとね、ゆっくり。"},
{id:"c668",type:"chunk",en:"Better late than never.",ja:"遅くてもやらないよりまし。"},
{id:"c669",type:"chunk",en:"Now or never.",ja:"今しかない。"},
{id:"c670",type:"chunk",en:"More or less.",ja:"だいたい。"},
{id:"c671",type:"chunk",en:"Sooner or later.",ja:"遅かれ早かれ。"},
{id:"c672",type:"chunk",en:"Sort of.",ja:"なんか〜みたいな。"},
{id:"c673",type:"chunk",en:"Kind of.",ja:"ちょっと〜って感じ。"},
{id:"c674",type:"chunk",en:"A little bit.",ja:"ちょっとだけ。"},
{id:"c675",type:"chunk",en:"Not really.",ja:"そうでもない。"},
{id:"c676",type:"chunk",en:"Hardly ever.",ja:"めったにない。"},
{id:"c677",type:"chunk",en:"You bet.",ja:"もちろん。"},
{id:"c678",type:"chunk",en:"You got it.",ja:"了解。"},
{id:"c679",type:"chunk",en:"Fair enough.",ja:"なるほどね。"},
// 了解・返事
{id:"c680",type:"chunk",en:"Got it.",ja:"了解。"},
{id:"c681",type:"chunk",en:"Roger that.",ja:"了解しました。"},
{id:"c682",type:"chunk",en:"Copy that.",ja:"了解。"},
{id:"c683",type:"chunk",en:"Heard.",ja:"聞いたよ。"},
{id:"c684",type:"chunk",en:"Noted.",ja:"了解しました。"},
{id:"c685",type:"chunk",en:"Understood.",ja:"わかりました。"},
{id:"c686",type:"chunk",en:"For sure.",ja:"確かに。"},
{id:"c687",type:"chunk",en:"Sounds good.",ja:"いいね。"},
{id:"c688",type:"chunk",en:"Will do.",ja:"そうします。"},
{id:"c689",type:"chunk",en:"Done and done.",ja:"完了完了。"},
// 会話のきっかけ
{id:"c690",type:"chunk",en:"Mind if I join you?",ja:"一緒にしてもいい？"},
{id:"c691",type:"chunk",en:"Is this seat taken?",ja:"この席空いてますか？"},
{id:"c692",type:"chunk",en:"Have we met?",ja:"前に会ったことある？"},
{id:"c693",type:"chunk",en:"Don't I know you?",ja:"どこかでお会いしませんでしたか？"},
{id:"c694",type:"chunk",en:"Long time!",ja:"久しぶり！"},
{id:"c695",type:"chunk",en:"Fancy meeting you here.",ja:"こんなところで会うとはね。"},
{id:"c696",type:"chunk",en:"What a coincidence!",ja:"なんて偶然！"},
{id:"c697",type:"chunk",en:"Small world.",ja:"世間は狭いね。"},
{id:"c698",type:"chunk",en:"It's been a minute.",ja:"しばらくぶり。"},
{id:"c699",type:"chunk",en:"How's it been?",ja:"最近どうだった？"},
{id:"c700",type:"chunk",en:"What's the story?",ja:"何の話？"},
];
